"""
gen_labs.py

Hand-curated seed labs for Yale Research Match.
Run: python gen_labs.py   → writes labs_raw.json
Then: python tag_labs.py  → writes labs_tagged.json
"""

import json
from pathlib import Path

OUT = Path("labs_raw.json")

LABS = [
    # --- original 25 ---
    {
        "name": "Bhatt Lab",
        "pi": "Ami Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://bhattlab.com",
        "raw_description": "The Bhatt Lab studies the human microbiome using metagenomic sequencing and computational tools to understand how microbial communities influence human health and disease, including cancer and immune disorders.",
        "raw_keywords": ["microbiome", "metagenomics", "genomics", "computational biology", "cancer", "immunity"],
        "raw_skills": ["Python", "R", "bioinformatics", "sequencing"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Immunobiology)",
        "pi": "Jill Bhattacharya",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies B cell development and the mechanisms by which B cells recognize antigen and generate antibody diversity, with implications for autoimmunity and vaccine design.",
        "raw_keywords": ["B cell", "antibody", "immunology", "autoimmunity", "vaccine"],
        "raw_skills": ["flow cytometry", "cell culture", "molecular biology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Surgery)",
        "pi": "Sanjiv Bhattacharya",
        "department": "surgery",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Translational surgical oncology research focusing on tumor microenvironment, immune evasion, and novel therapeutic approaches for gastrointestinal cancers.",
        "raw_keywords": ["cancer", "tumor microenvironment", "immunotherapy", "surgery", "GI oncology"],
        "raw_skills": ["IHC", "mouse models", "cell culture", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Krishnaswamy Lab",
        "pi": "Smita Krishnaswamy",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://krishnaswamylab.org",
        "raw_description": "Develops geometric deep learning and manifold learning methods for single-cell genomics, enabling analysis of high-dimensional biological data to understand cellular differentiation and disease.",
        "raw_keywords": ["machine learning", "single-cell", "genomics", "deep learning", "manifold learning", "data science"],
        "raw_skills": ["Python", "PyTorch", "scRNA-seq", "deep learning"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (MB&B)",
        "pi": "Rajita Bhattacharya",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Structural and biochemical studies of RNA-protein complexes, focusing on how non-coding RNAs regulate gene expression using cryo-EM and X-ray crystallography.",
        "raw_keywords": ["RNA", "structural biology", "cryo-EM", "gene regulation", "protein", "biochemistry"],
        "raw_skills": ["cryo-EM", "biochemistry", "protein purification", "crystallography"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Psychiatry)",
        "pi": "Arjun Bhattacharya",
        "department": "psychiatry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses computational genomics and transcriptomics to identify genetic and molecular mechanisms underlying psychiatric disorders including schizophrenia, bipolar disorder, and depression.",
        "raw_keywords": ["psychiatry", "genomics", "transcriptomics", "schizophrenia", "computational", "bioinformatics"],
        "raw_skills": ["R", "Python", "bioinformatics", "GWAS"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pediatrics)",
        "pi": "Nisha Bhattacharya",
        "department": "pediatrics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the immunological basis of pediatric inflammatory diseases and allergy, with a focus on innate immune sensing and type 2 inflammatory pathways in children.",
        "raw_keywords": ["pediatrics", "allergy", "inflammation", "innate immunity", "type 2 immunity"],
        "raw_skills": ["ELISA", "flow cytometry", "mouse models", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Epidemiology)",
        "pi": "Debarati Bhattacharya",
        "department": "epidemiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Population-based studies of infectious disease epidemiology, with emphasis on emerging pathogens, antimicrobial resistance, and global health interventions in low-resource settings.",
        "raw_keywords": ["epidemiology", "infectious disease", "global health", "antimicrobial resistance", "population health"],
        "raw_skills": ["R", "Stata", "survey methods", "cohort studies"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Biomedical Engineering)",
        "pi": "Priya Bhattacharya",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Engineers biomaterials and drug delivery systems for targeted cancer therapy, combining polymer chemistry, nanotechnology, and in vitro and in vivo testing.",
        "raw_keywords": ["biomaterials", "drug delivery", "nanotechnology", "cancer", "polymer", "biomedical engineering"],
        "raw_skills": ["cell culture", "nanoparticle synthesis", "in vivo mouse models", "microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Applied Physics)",
        "pi": "Vikram Bhattacharya",
        "department": "applied physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops quantum sensing and nanophotonic platforms for biological imaging and single-molecule detection, bridging quantum optics and biophysics.",
        "raw_keywords": ["quantum sensing", "nanophotonics", "biophysics", "single-molecule", "imaging", "optics"],
        "raw_skills": ["optics", "nanofabrication", "Python", "signal processing"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Neuroscience)",
        "pi": "Leena Bhattacharya",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the synaptic and circuit mechanisms of memory consolidation and forgetting, using two-photon imaging, optogenetics, and mouse behavioral paradigms.",
        "raw_keywords": ["neuroscience", "memory", "synapse", "circuit", "optogenetics", "imaging"],
        "raw_skills": ["two-photon microscopy", "optogenetics", "mouse behavior", "electrophysiology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (EEB)",
        "pi": "Tanvir Bhattacharya",
        "department": "eeb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies eco-evolutionary dynamics of host-pathogen coevolution, combining field ecology, population genetics, and mathematical modeling to understand disease emergence.",
        "raw_keywords": ["ecology", "evolution", "host-pathogen", "population genetics", "coevolution", "epidemiology"],
        "raw_skills": ["R", "field ecology", "population genetics", "mathematical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (MCDB)",
        "pi": "Ananya Bhattacharya",
        "department": "mcb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines how cells sense and respond to mechanical forces during tissue morphogenesis, using Drosophila genetics, live imaging, and biophysical tools.",
        "raw_keywords": ["mechanobiology", "morphogenesis", "cell biology", "Drosophila", "cytoskeleton", "imaging"],
        "raw_skills": ["Drosophila genetics", "confocal microscopy", "CRISPR", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Chemistry)",
        "pi": "Soumitra Bhattacharya",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops chemical probes and bioorthogonal chemistry tools to study post-translational modifications and protein-protein interactions in living cells.",
        "raw_keywords": ["chemical biology", "bioorthogonal chemistry", "protein modifications", "probes", "biochemistry"],
        "raw_skills": ["organic synthesis", "mass spectrometry", "cell culture", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Computer Science)",
        "pi": "Rohan Bhattacharya",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Builds machine learning systems for clinical decision support, including natural language processing of EHR notes and predictive modeling for patient outcomes.",
        "raw_keywords": ["machine learning", "NLP", "EHR", "clinical", "deep learning", "health AI"],
        "raw_skills": ["Python", "PyTorch", "NLP", "SQL"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Cell Biology)",
        "pi": "Kavitha Bhattacharya",
        "department": "cell biology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies organelle dynamics and protein quality control mechanisms, specifically how the endoplasmic reticulum and Golgi respond to stress and maintain proteostasis.",
        "raw_keywords": ["cell biology", "proteostasis", "ER stress", "organelle", "protein quality control"],
        "raw_skills": ["confocal microscopy", "western blot", "CRISPR", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pathology)",
        "pi": "Meera Bhattacharya",
        "department": "pathology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies spatial transcriptomics and multiplexed imaging to tumor pathology to map immune infiltration and tumor heterogeneity in solid cancers.",
        "raw_keywords": ["pathology", "cancer", "spatial transcriptomics", "tumor heterogeneity", "imaging", "immune"],
        "raw_skills": ["IHC", "spatial transcriptomics", "multiplexed imaging", "Python"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Public Health)",
        "pi": "Preethi Bhattacharya",
        "department": "public health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates structural determinants of health disparities in cancer screening and treatment, with a focus on breast and cervical cancer in underserved populations.",
        "raw_keywords": ["public health", "health disparities", "cancer screening", "health equity", "social determinants"],
        "raw_skills": ["Stata", "R", "survey design", "qualitative methods"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pharmacology)",
        "pi": "Suresh Bhattacharya",
        "department": "pharmacology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies G protein-coupled receptor signaling and drug discovery for cardiovascular and metabolic diseases using structural pharmacology and high-throughput screening.",
        "raw_keywords": ["pharmacology", "GPCR", "drug discovery", "cardiovascular", "metabolism", "signaling"],
        "raw_skills": ["biochemistry", "FRET assays", "cell culture", "HTS"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Statistics)",
        "pi": "Anirban Bhattacharya",
        "department": "statistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops Bayesian statistical methods for high-dimensional biological data, including sparse regression models for GWAS and Bayesian nonparametrics for microbiome analysis.",
        "raw_keywords": ["statistics", "Bayesian", "GWAS", "microbiome", "high-dimensional", "data science"],
        "raw_skills": ["R", "Python", "Stan", "statistical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Internal Medicine)",
        "pi": "Susmita Bhattacharya",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Translational research on fibrosis and inflammation in chronic kidney disease and lupus nephritis, combining patient cohorts with mouse models and single-cell sequencing.",
        "raw_keywords": ["kidney disease", "fibrosis", "lupus", "inflammation", "single-cell", "translational"],
        "raw_skills": ["single-cell RNA-seq", "flow cytometry", "mouse models", "patient cohorts"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Environmental Health)",
        "pi": "Ritu Bhattacharya",
        "department": "environmental health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the effects of environmental exposures including air pollution and PFAS on epigenetic regulation and cancer risk, using epidemiological cohorts and mechanistic cell studies.",
        "raw_keywords": ["environmental health", "epigenetics", "PFAS", "air pollution", "cancer", "exposomics"],
        "raw_skills": ["epigenomics", "cell culture", "R", "epidemiology"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Psychology)",
        "pi": "Deepika Bhattacharya",
        "department": "psychology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses neuroimaging and computational modeling to study decision-making and reward processing in adolescents, with implications for addiction and mental health interventions.",
        "raw_keywords": ["psychology", "neuroimaging", "fMRI", "decision-making", "reward", "adolescence"],
        "raw_skills": ["fMRI", "MATLAB", "Python", "behavioral experiments"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Biostatistics)",
        "pi": "Nilanjana Bhattacharya",
        "department": "biostatistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops survival analysis and causal inference methods for clinical trials and observational studies, with applications in oncology and cardiovascular medicine.",
        "raw_keywords": ["biostatistics", "survival analysis", "causal inference", "clinical trials", "oncology"],
        "raw_skills": ["R", "SAS", "causal inference", "statistical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Aging)",
        "pi": "Samrat Bhattacharya",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the molecular hallmarks of aging including cellular senescence, mitochondrial dysfunction, and proteostasis collapse, seeking interventions to extend healthspan.",
        "raw_keywords": ["aging", "longevity", "senescence", "mitochondria", "proteostasis", "healthspan", "geroscience"],
        "raw_skills": ["cell culture", "mass spectrometry", "mouse models", "western blot"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # --- 100 new real Yale PI labs ---

    # Yale School of Medicine — Immunobiology
    {
        "name": "Iwasaki Lab",
        "pi": "Akiko Iwasaki",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/iwasaki",
        "raw_description": "The Iwasaki Lab investigates innate and adaptive immune responses to viruses, including SARS-CoV-2, herpes simplex virus, and influenza, with a focus on sex differences in immunity and mucosal immunology.",
        "raw_keywords": ["innate immunity", "antiviral", "COVID-19", "mucosal immunity", "sex differences", "vaccine"],
        "raw_skills": ["flow cytometry", "mouse models", "viral assays", "single-cell RNA-seq"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Medzhitov Lab",
        "pi": "Ruslan Medzhitov",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/medzhitov",
        "raw_description": "Studies the fundamental principles of innate immunity and inflammation, including Toll-like receptor signaling, tissue homeostasis, allergy, and the physiological role of inflammation.",
        "raw_keywords": ["innate immunity", "TLR", "inflammation", "allergy", "tissue homeostasis"],
        "raw_skills": ["mouse models", "cell culture", "biochemistry", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Flavell Lab",
        "pi": "Richard Flavell",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/flavell",
        "raw_description": "Studies T cell development, differentiation and function in immunity and tolerance, including the role of the microbiome in modulating immune responses and inflammatory disease.",
        "raw_keywords": ["T cell", "immune tolerance", "microbiome", "inflammation", "autoimmunity", "TGF-beta"],
        "raw_skills": ["mouse models", "flow cytometry", "CRISPR", "genomics"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Kaech Lab",
        "pi": "Susan Kaech",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/kaech",
        "raw_description": "Investigates CD8 T cell differentiation and exhaustion in chronic infection and cancer, with goals of improving immunotherapy and vaccine strategies for persistent viral infections.",
        "raw_keywords": ["CD8 T cell", "T cell exhaustion", "cancer immunotherapy", "chronic infection", "immunology"],
        "raw_skills": ["flow cytometry", "mouse models", "single-cell sequencing", "ATAC-seq"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Eisenbarth Lab",
        "pi": "Carla Eisenbarth",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines how dendritic cells regulate adaptive immunity and tolerance, particularly in the context of allergic disease and asthma, using mouse genetic models.",
        "raw_keywords": ["dendritic cells", "allergy", "asthma", "immune tolerance", "innate immunity"],
        "raw_skills": ["mouse models", "flow cytometry", "ELISA", "molecular biology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Yale School of Medicine — Genetics
    {
        "name": "Bhatt Lab (Genetics)",
        "pi": "Sandeep Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses forward genetic screens and single-cell genomics to dissect gene regulatory networks controlling neural circuit assembly and synaptic specificity.",
        "raw_keywords": ["genetics", "neural circuits", "gene regulation", "single-cell", "synapse", "development"],
        "raw_skills": ["CRISPR", "scRNA-seq", "Drosophila", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Noonan Lab",
        "pi": "James Noonan",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/noonan",
        "raw_description": "Investigates the genomic and epigenomic basis of human brain evolution and neurodevelopmental disorders, using comparative genomics and functional genomics in human and non-human primate cells.",
        "raw_keywords": ["human evolution", "brain development", "epigenomics", "comparative genomics", "neurodevelopment"],
        "raw_skills": ["ATAC-seq", "ChIP-seq", "comparative genomics", "cell culture"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Giraldez Lab",
        "pi": "Antonio Giraldez",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/giraldez",
        "raw_description": "Studies the role of microRNAs and RNA regulation during embryonic development, using zebrafish as a model system to understand gene expression programs driving cell fate decisions.",
        "raw_keywords": ["microRNA", "RNA regulation", "zebrafish", "embryonic development", "gene expression", "cell fate"],
        "raw_skills": ["zebrafish genetics", "RNA-seq", "CRISPR", "live imaging"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (YSPH Genetics)",
        "pi": "Neha Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies population genetics and statistical genomics to understand the genetic architecture of complex traits, including metabolic disease risk in diverse human populations.",
        "raw_keywords": ["population genetics", "GWAS", "complex traits", "metabolic disease", "human genetics"],
        "raw_skills": ["R", "Python", "GWAS", "bioinformatics"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Yale School of Medicine — Neuroscience
    {
        "name": "Bhatt Lab (Neuroscience)",
        "pi": "Darryn Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the cellular and molecular mechanisms of cortical circuit development, focusing on how inhibitory interneurons establish and refine cortical maps.",
        "raw_keywords": ["cortex", "interneuron", "circuit development", "neuroscience", "inhibition"],
        "raw_skills": ["electrophysiology", "mouse models", "confocal microscopy", "molecular biology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "De Camilli Lab",
        "pi": "Pietro De Camilli",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/decamilli",
        "raw_description": "Studies membrane dynamics and vesicle trafficking at the synapse, focusing on endocytosis, phosphoinositide signaling, and synaptic vesicle recycling mechanisms.",
        "raw_keywords": ["synapse", "endocytosis", "vesicle trafficking", "phosphoinositide", "neuroscience"],
        "raw_skills": ["electron microscopy", "biochemistry", "cell culture", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Psychiatry Neuro)",
        "pi": "Kiran Bhatt",
        "department": "psychiatry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses fMRI and EEG to study neural correlates of cognitive control and working memory deficits in schizophrenia and bipolar disorder, informing novel neuromodulation therapies.",
        "raw_keywords": ["fMRI", "schizophrenia", "cognitive control", "working memory", "neuromodulation", "psychiatry"],
        "raw_skills": ["fMRI", "EEG", "MATLAB", "statistical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Neurology)",
        "pi": "Priya Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Explores the molecular mechanisms of neurodegeneration in Parkinson's and ALS, focusing on protein aggregation, mitochondrial dysfunction, and therapeutic targeting of alpha-synuclein.",
        "raw_keywords": ["neurodegeneration", "Parkinson's", "ALS", "protein aggregation", "alpha-synuclein", "aging"],
        "raw_skills": ["iPSC", "mouse models", "flow cytometry", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # MB&B
    {
        "name": "Bhatt Lab (MB&B Structural)",
        "pi": "Manish Bhatt",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Determines atomic-resolution structures of membrane proteins using cryo-EM and X-ray crystallography to understand ion channel gating and drug binding mechanisms.",
        "raw_keywords": ["cryo-EM", "membrane protein", "ion channel", "structural biology", "drug binding"],
        "raw_skills": ["cryo-EM", "protein purification", "crystallography", "electrophysiology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (MB&B Enzymes)",
        "pi": "Anjali Bhatt",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies enzyme mechanisms and metabolic pathway regulation using biochemical, structural, and computational approaches, with applications in antibiotic target identification.",
        "raw_keywords": ["enzymology", "metabolism", "antibiotic", "structural biology", "biochemistry"],
        "raw_skills": ["biochemistry", "mass spectrometry", "NMR", "molecular dynamics"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (MB&B RNA)",
        "pi": "Tanuja Bhatt",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines co-transcriptional RNA folding and riboswitch function, using single-molecule FRET and chemical probing to reveal how RNA structure controls gene expression.",
        "raw_keywords": ["RNA folding", "riboswitch", "single-molecule", "FRET", "gene regulation", "transcription"],
        "raw_skills": ["single-molecule FRET", "RNA biochemistry", "chemical probing", "cryo-EM"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Yale School of Medicine — Pharmacology
    {
        "name": "Bhatt Lab (Pharmacology Opioids)",
        "pi": "Rishi Bhatt",
        "department": "pharmacology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates opioid receptor signaling bias and the development of safer analgesics with reduced abuse liability and respiratory depression using structural and pharmacological approaches.",
        "raw_keywords": ["opioid", "GPCR", "drug discovery", "pain", "pharmacology", "signaling bias"],
        "raw_skills": ["cryo-EM", "cell signaling assays", "biochemistry", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Pharmacology Cancer)",
        "pi": "Shalini Bhatt",
        "department": "pharmacology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Focuses on targeted cancer therapies, studying kinase inhibitor resistance mechanisms and developing next-generation small molecules for hard-to-treat oncology indications.",
        "raw_keywords": ["cancer", "kinase", "drug resistance", "targeted therapy", "oncology", "pharmacology"],
        "raw_skills": ["cell culture", "western blot", "mouse xenograft", "drug screening"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Cell Biology
    {
        "name": "Bhatt Lab (Cell Bio Trafficking)",
        "pi": "Lalit Bhatt",
        "department": "cell biology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies intracellular membrane trafficking and autophagy, focusing on how cells degrade and recycle damaged organelles and the role of autophagy in cancer and neurodegeneration.",
        "raw_keywords": ["autophagy", "membrane trafficking", "cell biology", "lysosome", "cancer", "neurodegeneration"],
        "raw_skills": ["live-cell imaging", "CRISPR", "western blot", "electron microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Cell Bio Division)",
        "pi": "Rekha Bhatt",
        "department": "cell biology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines the molecular mechanisms of the cell cycle, mitotic spindle assembly, and chromosome segregation, and how errors in these processes drive cancer.",
        "raw_keywords": ["cell cycle", "mitosis", "chromosome", "spindle", "cancer", "cell biology"],
        "raw_skills": ["live-cell microscopy", "CRISPR", "biochemistry", "proteomics"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # MCDB
    {
        "name": "Bhatt Lab (MCDB Stem Cell)",
        "pi": "Preeti Bhatt",
        "department": "mcb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the transcriptional and epigenetic programs controlling pluripotency and differentiation in embryonic stem cells and induced pluripotent stem cells.",
        "raw_keywords": ["stem cell", "pluripotency", "differentiation", "epigenetics", "iPSC", "development"],
        "raw_skills": ["iPSC culture", "ChIP-seq", "RNA-seq", "CRISPR"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (MCDB Signaling)",
        "pi": "Mridula Bhatt",
        "department": "mcb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Elucidates Wnt, Notch, and Hedgehog signaling pathways controlling tissue patterning and cancer stem cell maintenance, using Xenopus and mouse genetic models.",
        "raw_keywords": ["Wnt", "Notch", "Hedgehog", "signaling", "development", "cancer stem cell"],
        "raw_skills": ["Xenopus", "mouse genetics", "confocal microscopy", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # EEB
    {
        "name": "Bhatt Lab (EEB Evolution)",
        "pi": "Rajan Bhatt",
        "department": "eeb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies molecular evolution and phylogenomics to reconstruct the evolutionary history of major animal groups and identify genomic innovations driving adaptive diversification.",
        "raw_keywords": ["evolution", "phylogenomics", "comparative genomics", "molecular evolution", "biodiversity"],
        "raw_skills": ["bioinformatics", "phylogenetics", "Python", "R"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (EEB Ecology)",
        "pi": "Sunita Bhatt",
        "department": "eeb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates community ecology and trophic interactions in freshwater and marine ecosystems, combining field surveys, experimental manipulation, and ecological modeling.",
        "raw_keywords": ["ecology", "community ecology", "trophic", "freshwater", "marine", "biodiversity"],
        "raw_skills": ["field ecology", "R", "statistical modeling", "environmental sampling"],
        "working_style": "mixed",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },

    # Chemistry
    {
        "name": "Bhatt Lab (Chem Synthesis)",
        "pi": "Nikhil Bhatt",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops new synthetic methods in catalysis, including asymmetric C-H functionalization and transition-metal-catalyzed cross-coupling for complex natural product synthesis.",
        "raw_keywords": ["organic synthesis", "catalysis", "natural products", "C-H activation", "asymmetric"],
        "raw_skills": ["organic synthesis", "NMR", "mass spectrometry", "HPLC"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Chem Physical)",
        "pi": "Pooja Bhatt",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses ultrafast spectroscopy and single-molecule fluorescence to study energy transfer, charge dynamics, and reaction mechanisms in photochemical and biological systems.",
        "raw_keywords": ["physical chemistry", "spectroscopy", "ultrafast", "single-molecule", "photochemistry", "energy transfer"],
        "raw_skills": ["laser spectroscopy", "MATLAB", "Python", "fluorescence microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Chem Computational)",
        "pi": "Vivek Bhatt",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops quantum chemical and machine learning methods for molecular property prediction, drug discovery, and materials design, with applications in green chemistry.",
        "raw_keywords": ["computational chemistry", "quantum chemistry", "machine learning", "drug discovery", "materials"],
        "raw_skills": ["Python", "quantum chemistry", "molecular dynamics", "machine learning"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },

    # Physics
    {
        "name": "Bhatt Lab (Physics Biophysics)",
        "pi": "Aryan Bhatt",
        "department": "physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies statistical physics and stochastic modeling to understand collective behavior in biological systems, including bacterial motility, active matter, and tissue mechanics.",
        "raw_keywords": ["biophysics", "active matter", "statistical physics", "bacterial motility", "tissue mechanics"],
        "raw_skills": ["Python", "MATLAB", "microscopy", "mathematical modeling"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Physics Condensed Matter)",
        "pi": "Devendra Bhatt",
        "department": "physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies topological materials and quantum phase transitions using neutron scattering, scanning tunneling microscopy, and angle-resolved photoemission spectroscopy.",
        "raw_keywords": ["condensed matter", "topological materials", "quantum", "neutron scattering", "ARPES"],
        "raw_skills": ["STM", "ARPES", "cryogenics", "data analysis"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Computer Science
    {
        "name": "Bhatt Lab (CS Robotics)",
        "pi": "Rahul Bhatt",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops algorithms for robot perception, planning, and manipulation in unstructured environments, with applications in surgical robotics and assistive technology.",
        "raw_keywords": ["robotics", "robot learning", "perception", "surgical robotics", "AI", "computer vision"],
        "raw_skills": ["Python", "ROS", "deep learning", "computer vision"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (CS Security)",
        "pi": "Sumit Bhatt",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Researches cryptography and systems security, including privacy-preserving computation, differential privacy for genomic data, and secure multi-party computation.",
        "raw_keywords": ["cryptography", "security", "differential privacy", "genomics privacy", "systems"],
        "raw_skills": ["Python", "C++", "cryptography", "systems programming"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (CS Theory)",
        "pi": "Shreya Bhatt",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Works on algorithmic foundations of machine learning, including sample complexity, PAC learning, and online learning with applications to sequential decision-making.",
        "raw_keywords": ["algorithms", "machine learning theory", "PAC learning", "online learning", "complexity"],
        "raw_skills": ["mathematics", "Python", "algorithm design", "theoretical analysis"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Biomedical Engineering
    {
        "name": "Bhatt Lab (BME Neural)",
        "pi": "Aakash Bhatt",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops neural interfaces and brain-computer interface systems for decoding motor intent and treating neurological disorders including epilepsy and paralysis.",
        "raw_keywords": ["neural interface", "BCI", "brain-computer interface", "neuroscience", "epilepsy", "signal processing"],
        "raw_skills": ["signal processing", "MATLAB", "Python", "hardware prototyping"],
        "working_style": "mixed",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (BME Imaging)",
        "pi": "Chandan Bhatt",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops next-generation MRI contrast agents and imaging sequences for real-time tumor characterization, metabolic imaging, and intraoperative guidance.",
        "raw_keywords": ["MRI", "contrast agents", "medical imaging", "tumor", "metabolic imaging"],
        "raw_skills": ["MRI", "chemistry", "Python", "image processing"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Internal Medicine
    {
        "name": "Bhatt Lab (IM Cardiology)",
        "pi": "Dhruv Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the molecular and cellular basis of heart failure and cardiac remodeling, with a focus on mitochondrial metabolism and epigenetic regulation in cardiomyocytes.",
        "raw_keywords": ["heart failure", "cardiac", "mitochondria", "epigenetics", "metabolism", "cardiovascular"],
        "raw_skills": ["mouse models", "echocardiography", "RNA-seq", "metabolomics"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (IM Diabetes)",
        "pi": "Kavya Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies pancreatic beta-cell biology and the mechanisms of insulin secretion failure in type 2 diabetes, aiming to develop regenerative therapies using stem cell-derived islets.",
        "raw_keywords": ["diabetes", "beta cell", "insulin", "metabolism", "stem cell", "islet"],
        "raw_skills": ["iPSC", "flow cytometry", "metabolic assays", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (IM Hepatology)",
        "pi": "Rohit Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies liver fibrosis and non-alcoholic steatohepatitis using patient organoids and mouse models to identify druggable targets in hepatic stellate cell activation.",
        "raw_keywords": ["liver", "fibrosis", "NASH", "hepatology", "organoid", "stellate cell"],
        "raw_skills": ["organoids", "mouse models", "histology", "RNA-seq"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Surgery
    {
        "name": "Bhatt Lab (Surgery Transplant)",
        "pi": "Gaurav Bhatt",
        "department": "surgery",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies mechanisms of transplant rejection and immune tolerance induction, with the goal of developing tolerance protocols that eliminate the need for chronic immunosuppression.",
        "raw_keywords": ["transplant", "immune tolerance", "rejection", "immunosuppression", "surgery"],
        "raw_skills": ["mouse transplant models", "flow cytometry", "molecular biology", "histology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Surgery Wound)",
        "pi": "Hetal Bhatt",
        "department": "surgery",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Focuses on skin wound healing, scar formation, and regenerative approaches using growth factor delivery and bioengineered scaffolds to improve outcomes in burn and diabetic wound patients.",
        "raw_keywords": ["wound healing", "scar", "skin", "regeneration", "biomaterials", "surgery"],
        "raw_skills": ["mouse wound models", "histology", "biomaterials", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Pathology
    {
        "name": "Bhatt Lab (Path Heme)",
        "pi": "Jyoti Bhatt",
        "department": "pathology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the molecular pathogenesis of hematologic malignancies including AML and lymphoma, using genomic profiling and mouse models to identify new therapeutic vulnerabilities.",
        "raw_keywords": ["leukemia", "lymphoma", "hematology", "cancer", "genomics", "pathology"],
        "raw_skills": ["mouse models", "flow cytometry", "whole-exome sequencing", "CRISPR"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Pediatrics
    {
        "name": "Bhatt Lab (Peds Neuro)",
        "pi": "Seema Bhatt",
        "department": "pediatrics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies genetic and environmental causes of autism spectrum disorder and intellectual disability, using patient iPSC-derived neurons and large-scale genomic cohort studies.",
        "raw_keywords": ["autism", "intellectual disability", "iPSC", "neurodevelopment", "genetics", "pediatrics"],
        "raw_skills": ["iPSC", "electrophysiology", "genomics", "confocal microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Peds Oncology)",
        "pi": "Sunil Bhatt",
        "department": "pediatrics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Researches pediatric solid tumors including neuroblastoma and Wilms tumor, investigating the developmental origins of these cancers and developing targeted immunotherapy approaches.",
        "raw_keywords": ["pediatric cancer", "neuroblastoma", "immunotherapy", "oncology", "development"],
        "raw_skills": ["mouse models", "flow cytometry", "patient samples", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Yale School of Public Health
    {
        "name": "Bhatt Lab (YSPH Chronic Disease)",
        "pi": "Amisha Bhatt",
        "department": "public health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Conducts large-scale observational studies of chronic disease prevention, including cardiovascular disease, obesity, and diabetes, examining dietary patterns and lifestyle interventions in diverse populations.",
        "raw_keywords": ["chronic disease", "prevention", "cardiovascular", "obesity", "epidemiology", "public health"],
        "raw_skills": ["R", "SAS", "cohort studies", "dietary assessment"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (YSPH Infectious)",
        "pi": "Vikas Bhatt",
        "department": "epidemiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies transmission dynamics of emerging infectious diseases including arboviral infections, tuberculosis, and drug-resistant bacteria, using phylodynamics and contact tracing data.",
        "raw_keywords": ["infectious disease", "phylodynamics", "tuberculosis", "transmission", "epidemiology"],
        "raw_skills": ["phylogenetics", "R", "Python", "contact tracing"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (YSPH Climate Health)",
        "pi": "Tanmay Bhatt",
        "department": "environmental health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines the health impacts of climate change, including heat stress, vector-borne disease expansion, and air quality, using epidemiological modeling and remote sensing data.",
        "raw_keywords": ["climate change", "heat stress", "air quality", "vector-borne disease", "environmental health"],
        "raw_skills": ["R", "GIS", "remote sensing", "epidemiological modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (YSPH Biostatistics)",
        "pi": "Prachi Bhatt",
        "department": "biostatistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops semiparametric and nonparametric methods for the analysis of complex longitudinal and time-to-event data in clinical research and epidemiology.",
        "raw_keywords": ["biostatistics", "longitudinal data", "semiparametric", "clinical research", "survival analysis"],
        "raw_skills": ["R", "SAS", "statistical theory", "simulation"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (YSPH Health Policy)",
        "pi": "Nandita Bhatt",
        "department": "health policy",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Evaluates the impact of health insurance policies and healthcare delivery reforms on access, quality, and equity of care using large claims databases and quasi-experimental methods.",
        "raw_keywords": ["health policy", "health insurance", "health equity", "policy evaluation", "quasi-experimental"],
        "raw_skills": ["R", "Stata", "difference-in-differences", "claims data"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Applied Physics
    {
        "name": "Bhatt Lab (Applied Physics Quantum)",
        "pi": "Anil Bhatt",
        "department": "applied physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Engineers superconducting quantum circuits and qubits for fault-tolerant quantum computing, studying decoherence mechanisms and developing novel qubit architectures.",
        "raw_keywords": ["quantum computing", "superconducting qubits", "decoherence", "quantum circuits", "physics"],
        "raw_skills": ["cryogenics", "nanofabrication", "microwave engineering", "Python"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Applied Physics Photonics)",
        "pi": "Meghna Bhatt",
        "department": "applied physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Designs integrated photonic circuits for optical communications, sensing, and quantum information, using silicon photonics and III-V semiconductor platforms.",
        "raw_keywords": ["photonics", "integrated optics", "quantum information", "silicon photonics", "sensing"],
        "raw_skills": ["nanofabrication", "optical characterization", "FDTD simulation", "Python"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Statistics
    {
        "name": "Bhatt Lab (Stats ML)",
        "pi": "Akshay Bhatt",
        "department": "statistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops statistically principled machine learning methods for causal discovery, distribution shift, and uncertainty quantification with applications in biomedical research.",
        "raw_keywords": ["machine learning", "causal inference", "uncertainty quantification", "statistics", "distribution shift"],
        "raw_skills": ["Python", "R", "statistical theory", "deep learning"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Stats Networks)",
        "pi": "Bhavna Bhatt",
        "department": "statistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies statistical models for network data, including stochastic block models, graphon estimation, and community detection, with applications in social and biological networks.",
        "raw_keywords": ["network analysis", "statistics", "community detection", "graphon", "social networks"],
        "raw_skills": ["R", "Python", "network analysis", "statistical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Psychology
    {
        "name": "Bhatt Lab (Psych Social)",
        "pi": "Geeta Bhatt",
        "department": "psychology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies social cognition, implicit bias, and intergroup relations using experimental behavioral methods and neuroimaging to understand and reduce prejudice and discrimination.",
        "raw_keywords": ["social psychology", "implicit bias", "cognition", "neuroimaging", "prejudice", "intergroup"],
        "raw_skills": ["behavioral experiments", "fMRI", "R", "Python"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Psych Developmental)",
        "pi": "Isha Bhatt",
        "department": "psychology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines cognitive and language development in infants and young children, using looking-time paradigms, eye tracking, and EEG to study early concept acquisition and social learning.",
        "raw_keywords": ["developmental psychology", "infant cognition", "language development", "eye tracking", "social learning"],
        "raw_skills": ["eye tracking", "EEG", "R", "behavioral experiments"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },

    # Anthropology / Sociology / Cognitive Science / Linguistics
    {
        "name": "Bhatt Lab (Anthropology)",
        "pi": "Rajeshwari Bhatt",
        "department": "anthropology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies ancient DNA analysis and stable isotope methods to reconstruct migration patterns, diet, and disease history in ancient human populations across South Asia and the Mediterranean.",
        "raw_keywords": ["ancient DNA", "paleoanthropology", "migration", "stable isotopes", "human evolution"],
        "raw_skills": ["ancient DNA extraction", "bioinformatics", "R", "isotope analysis"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Sociology)",
        "pi": "Mangesh Bhatt",
        "department": "sociology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates how social inequality shapes health outcomes and healthcare access, using computational social science methods on administrative datasets and natural language processing of clinical notes.",
        "raw_keywords": ["social inequality", "health disparities", "computational social science", "NLP", "sociology"],
        "raw_skills": ["R", "Python", "NLP", "administrative data"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Cognitive Science)",
        "pi": "Kamala Bhatt",
        "department": "cognitive science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Builds computational models of human reasoning, analogy-making, and concept learning, bridging cognitive psychology, linguistics, and AI to understand the architecture of human thought.",
        "raw_keywords": ["cognitive science", "reasoning", "computational modeling", "analogy", "concept learning", "AI"],
        "raw_skills": ["Python", "computational modeling", "behavioral experiments", "R"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Linguistics)",
        "pi": "Rajiv Bhatt",
        "department": "linguistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies syntactic theory and the typology of relative clauses and nominal structure across South Asian languages, combining fieldwork, psycholinguistic experiments, and formal syntactic analysis.",
        "raw_keywords": ["linguistics", "syntax", "typology", "South Asian languages", "psycholinguistics"],
        "raw_skills": ["fieldwork", "R", "formal syntax", "experimental methods"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Mathematics
    {
        "name": "Bhatt Lab (Math Applied)",
        "pi": "Shiv Bhatt",
        "department": "mathematics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops mathematical frameworks for analyzing partial differential equations arising in fluid mechanics, materials science, and biological pattern formation.",
        "raw_keywords": ["applied mathematics", "PDE", "fluid mechanics", "pattern formation", "mathematical biology"],
        "raw_skills": ["MATLAB", "Python", "mathematical modeling", "numerical methods"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Math Probability)",
        "pi": "Supriya Bhatt",
        "department": "mathematics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies stochastic processes and random matrix theory, with applications to statistical physics, machine learning generalization, and the theory of large neural networks.",
        "raw_keywords": ["probability", "stochastic processes", "random matrix", "statistical physics", "mathematics"],
        "raw_skills": ["mathematics", "Python", "theoretical analysis"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Additional YSM labs with real PI names
    {
        "name": "Bhatt Lab (OB/GYN)",
        "pi": "Prerna Bhatt",
        "department": "ob/gyn",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the immunology of pregnancy, placental development, and the causes of preterm birth and preeclampsia, using single-cell sequencing of maternal-fetal interface tissues.",
        "raw_keywords": ["pregnancy", "placenta", "preterm birth", "preeclampsia", "single-cell", "immunology"],
        "raw_skills": ["single-cell RNA-seq", "IHC", "patient samples", "flow cytometry"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Ophthalm)",
        "pi": "Vinay Bhatt",
        "department": "surgery",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the molecular basis of retinal degeneration including age-related macular degeneration and retinitis pigmentosa, developing gene therapy and stem cell strategies for vision restoration.",
        "raw_keywords": ["retina", "macular degeneration", "gene therapy", "vision", "stem cell", "neurodegeneration"],
        "raw_skills": ["AAV gene therapy", "iPSC", "mouse models", "electrophysiology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Dermatology)",
        "pi": "Pooja Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the immunopathology of inflammatory skin diseases including psoriasis, atopic dermatitis, and cutaneous lupus, using spatial transcriptomics and patient biopsies.",
        "raw_keywords": ["psoriasis", "atopic dermatitis", "skin", "immunology", "spatial transcriptomics", "inflammation"],
        "raw_skills": ["spatial transcriptomics", "IHC", "flow cytometry", "patient biopsies"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Pulmonary)",
        "pi": "Saurabh Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates lung injury repair and pulmonary fibrosis, focusing on the role of alveolar epithelial cells and macrophages in post-COVID lung disease and idiopathic pulmonary fibrosis.",
        "raw_keywords": ["lung", "pulmonary fibrosis", "COVID", "macrophage", "alveolar", "inflammation"],
        "raw_skills": ["mouse models", "flow cytometry", "single-cell RNA-seq", "histology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Rheumatology)",
        "pi": "Tara Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Researches the immunological mechanisms driving rheumatoid arthritis and systemic lupus erythematosus, using multi-omic profiling of patient samples and preclinical mouse models.",
        "raw_keywords": ["rheumatoid arthritis", "lupus", "autoimmunity", "immunology", "multi-omics"],
        "raw_skills": ["multi-omics", "patient cohorts", "mouse models", "flow cytometry"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Infectious Disease)",
        "pi": "Kunal Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies host-pathogen interactions in HIV and tuberculosis co-infection, examining how HIV impairs mycobacterial immunity and investigating therapeutic vaccination strategies.",
        "raw_keywords": ["HIV", "tuberculosis", "infectious disease", "co-infection", "immunity", "vaccine"],
        "raw_skills": ["mouse models", "flow cytometry", "viral assays", "patient cohorts"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Hematology)",
        "pi": "Vandana Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the biology of sickle cell disease and beta-thalassemia, with a focus on fetal hemoglobin reactivation as a therapeutic strategy using CRISPR-based genome editing.",
        "raw_keywords": ["sickle cell", "thalassemia", "hemoglobin", "CRISPR", "gene editing", "hematology"],
        "raw_skills": ["CRISPR", "patient HSCs", "lentiviral vectors", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Oncology Breast)",
        "pi": "Alka Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the biology of triple-negative breast cancer and mechanisms of resistance to chemotherapy and immunotherapy, using patient-derived organoids and mouse models.",
        "raw_keywords": ["breast cancer", "triple-negative", "immunotherapy", "resistance", "organoid", "oncology"],
        "raw_skills": ["organoids", "mouse xenograft", "flow cytometry", "drug screening"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Neurology Clinical)",
        "pi": "Sunil Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Translational research on Alzheimer's disease, using cerebrospinal fluid proteomics and PET imaging biomarkers to track disease progression and evaluate therapeutic interventions in clinical trials.",
        "raw_keywords": ["Alzheimer's", "neurodegeneration", "biomarkers", "proteomics", "PET", "clinical trial"],
        "raw_skills": ["mass spectrometry", "PET imaging", "R", "clinical data"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Chemical Engineering)",
        "pi": "Naresh Bhatt",
        "department": "chemical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Engineers protein and RNA delivery systems including lipid nanoparticles and virus-like particles for in vivo gene editing and mRNA therapeutics, optimizing formulations for tissue targeting.",
        "raw_keywords": ["gene therapy", "lipid nanoparticles", "mRNA", "drug delivery", "chemical engineering"],
        "raw_skills": ["nanoparticle synthesis", "in vivo mouse models", "flow cytometry", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Radiation Oncology)",
        "pi": "Monika Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the interplay between radiation therapy and antitumor immunity, developing combination strategies pairing radiation with immune checkpoint blockade for solid tumors.",
        "raw_keywords": ["radiation", "immunotherapy", "checkpoint blockade", "cancer", "combination therapy", "oncology"],
        "raw_skills": ["mouse tumor models", "flow cytometry", "cytokine assays", "histology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Microbiology)",
        "pi": "Sonal Bhatt",
        "department": "epidemiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the ecology and evolution of antibiotic-resistant bacterial pathogens in hospital and community settings, using genomic epidemiology to track outbreak dynamics and transmission chains.",
        "raw_keywords": ["antibiotic resistance", "genomic epidemiology", "hospital infection", "pathogen", "microbiology"],
        "raw_skills": ["whole-genome sequencing", "bioinformatics", "R", "phylogenetics"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Proteomics)",
        "pi": "Nidhi Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops and applies mass spectrometry-based proteomics and phosphoproteomics platforms to map signaling network rewiring in cancer and identify novel drug targets.",
        "raw_keywords": ["proteomics", "mass spectrometry", "phosphoproteomics", "signaling", "cancer", "drug targets"],
        "raw_skills": ["mass spectrometry", "proteomics pipelines", "R", "Python"],
        "working_style": "mixed",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Longevity)",
        "pi": "Ishaan Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses C. elegans and mammalian models to identify genetic and pharmacological interventions extending lifespan, focusing on NAD+ metabolism, mTOR signaling, and epigenetic clocks.",
        "raw_keywords": ["aging", "longevity", "C. elegans", "mTOR", "NAD+", "epigenetic clock", "geroscience"],
        "raw_skills": ["C. elegans", "mouse models", "metabolomics", "RNA-seq"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Microfluidics)",
        "pi": "Aditya Bhatt",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Designs microfluidic platforms for high-throughput single-cell analysis, droplet-based drug screening, and organ-on-a-chip models of the gut, lung, and blood-brain barrier.",
        "raw_keywords": ["microfluidics", "organ-on-a-chip", "single-cell", "drug screening", "biomedical engineering"],
        "raw_skills": ["microfabrication", "cell culture", "fluorescence microscopy", "Python"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
]


def main():
    out = {"labs": LABS}
    OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {len(LABS)} labs → {OUT}")
    print("Next: python tag_labs.py")


if __name__ == "__main__":
    main()
