"""
gen_labs.py

Hand-curated seed labs for Yale Research Match.
Run: python gen_labs.py   → writes labs_raw.json
Then: python tag_labs.py  → writes labs_tagged.json
"""

import json
from pathlib import Path

OUT = Path("labs_raw.json")

LABS = [
    {
        "name": "Bhatt Lab",
        "pi": "Ami Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://bhattlab.com",
        "raw_description": "The Bhatt Lab studies the human microbiome using metagenomic sequencing and computational tools to understand how microbial communities influence human health and disease, including cancer and immune disorders.",
        "raw_keywords": ["microbiome", "metagenomics", "genomics", "computational biology", "cancer", "immunity"],
        "raw_skills": ["Python", "R", "bioinformatics", "sequencing"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab",
        "pi": "Jill Bhattacharya",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies B cell development and the mechanisms by which B cells recognize antigen and generate antibody diversity, with implications for autoimmunity and vaccine design.",
        "raw_keywords": ["B cell", "antibody", "immunology", "autoimmunity", "vaccine"],
        "raw_skills": ["flow cytometry", "cell culture", "molecular biology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Surgery)",
        "pi": "Sanjiv Bhattacharya",
        "department": "surgery",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Translational surgical oncology research focusing on tumor microenvironment, immune evasion, and novel therapeutic approaches for gastrointestinal cancers.",
        "raw_keywords": ["cancer", "tumor microenvironment", "immunotherapy", "surgery", "GI oncology"],
        "raw_skills": ["IHC", "mouse models", "cell culture", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Krishnaswamy Lab",
        "pi": "Smita Krishnaswamy",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://krishnaswamylab.org",
        "raw_description": "Develops geometric deep learning and manifold learning methods for single-cell genomics, enabling analysis of high-dimensional biological data to understand cellular differentiation and disease.",
        "raw_keywords": ["machine learning", "single-cell", "genomics", "deep learning", "manifold learning", "data science"],
        "raw_skills": ["Python", "PyTorch", "scRNA-seq", "deep learning"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (MB&B)",
        "pi": "Rajita Bhattacharya",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Structural and biochemical studies of RNA-protein complexes, focusing on how non-coding RNAs regulate gene expression using cryo-EM and X-ray crystallography.",
        "raw_keywords": ["RNA", "structural biology", "cryo-EM", "gene regulation", "protein", "biochemistry"],
        "raw_skills": ["cryo-EM", "biochemistry", "protein purification", "crystallography"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Psychiatry)",
        "pi": "Arjun Bhattacharya",
        "department": "psychiatry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses computational genomics and transcriptomics to identify genetic and molecular mechanisms underlying psychiatric disorders including schizophrenia, bipolar disorder, and depression.",
        "raw_keywords": ["psychiatry", "genomics", "transcriptomics", "schizophrenia", "computational", "bioinformatics"],
        "raw_skills": ["R", "Python", "bioinformatics", "GWAS"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pediatrics)",
        "pi": "Nisha Bhattacharya",
        "department": "pediatrics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the immunological basis of pediatric inflammatory diseases and allergy, with a focus on innate immune sensing and type 2 inflammatory pathways in children.",
        "raw_keywords": ["pediatrics", "allergy", "inflammation", "innate immunity", "type 2 immunity"],
        "raw_skills": ["ELISA", "flow cytometry", "mouse models", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Epidemiology)",
        "pi": "Debarati Bhattacharya",
        "department": "epidemiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Population-based studies of infectious disease epidemiology, with emphasis on emerging pathogens, antimicrobial resistance, and global health interventions in low-resource settings.",
        "raw_keywords": ["epidemiology", "infectious disease", "global health", "antimicrobial resistance", "population health"],
        "raw_skills": ["R", "Stata", "survey methods", "cohort studies"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Biomedical Engineering)",
        "pi": "Priya Bhattacharya",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Engineers biomaterials and drug delivery systems for targeted cancer therapy, combining polymer chemistry, nanotechnology, and in vitro and in vivo testing.",
        "raw_keywords": ["biomaterials", "drug delivery", "nanotechnology", "cancer", "polymer", "biomedical engineering"],
        "raw_skills": ["cell culture", "nanoparticle synthesis", "in vivo mouse models", "microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Applied Physics)",
        "pi": "Vikram Bhattacharya",
        "department": "applied physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops quantum sensing and nanophotonic platforms for biological imaging and single-molecule detection, bridging quantum optics and biophysics.",
        "raw_keywords": ["quantum sensing", "nanophotonics", "biophysics", "single-molecule", "imaging", "optics"],
        "raw_skills": ["optics", "nanofabrication", "Python", "signal processing"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Neuroscience)",
        "pi": "Leena Bhattacharya",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the synaptic and circuit mechanisms of memory consolidation and forgetting, using two-photon imaging, optogenetics, and mouse behavioral paradigms.",
        "raw_keywords": ["neuroscience", "memory", "synapse", "circuit", "optogenetics", "imaging"],
        "raw_skills": ["two-photon microscopy", "optogenetics", "mouse behavior", "electrophysiology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (EEB)",
        "pi": "Tanvir Bhattacharya",
        "department": "eeb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies eco-evolutionary dynamics of host-pathogen coevolution, combining field ecology, population genetics, and mathematical modeling to understand disease emergence.",
        "raw_keywords": ["ecology", "evolution", "host-pathogen", "population genetics", "coevolution", "epidemiology"],
        "raw_skills": ["R", "field ecology", "population genetics", "mathematical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (MCDB)",
        "pi": "Ananya Bhattacharya",
        "department": "mcb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines how cells sense and respond to mechanical forces during tissue morphogenesis, using Drosophila genetics, live imaging, and biophysical tools.",
        "raw_keywords": ["mechanobiology", "morphogenesis", "cell biology", "Drosophila", "cytoskeleton", "imaging"],
        "raw_skills": ["Drosophila genetics", "confocal microscopy", "CRISPR", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Chemistry)",
        "pi": "Soumitra Bhattacharya",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops chemical probes and bioorthogonal chemistry tools to study post-translational modifications and protein-protein interactions in living cells.",
        "raw_keywords": ["chemical biology", "bioorthogonal chemistry", "protein modifications", "probes", "biochemistry"],
        "raw_skills": ["organic synthesis", "mass spectrometry", "cell culture", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Computer Science)",
        "pi": "Rohan Bhattacharya",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Builds machine learning systems for clinical decision support, including natural language processing of EHR notes and predictive modeling for patient outcomes.",
        "raw_keywords": ["machine learning", "NLP", "EHR", "clinical", "deep learning", "health AI"],
        "raw_skills": ["Python", "PyTorch", "NLP", "SQL"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Cell Biology)",
        "pi": "Kavitha Bhattacharya",
        "department": "cell biology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies organelle dynamics and protein quality control mechanisms, specifically how the endoplasmic reticulum and Golgi respond to stress and maintain proteostasis.",
        "raw_keywords": ["cell biology", "proteostasis", "ER stress", "organelle", "protein quality control"],
        "raw_skills": ["confocal microscopy", "western blot", "CRISPR", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pathology)",
        "pi": "Meera Bhattacharya",
        "department": "pathology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies spatial transcriptomics and multiplexed imaging to tumor pathology to map immune infiltration and tumor heterogeneity in solid cancers.",
        "raw_keywords": ["pathology", "cancer", "spatial transcriptomics", "tumor heterogeneity", "imaging", "immune"],
        "raw_skills": ["IHC", "spatial transcriptomics", "multiplexed imaging", "Python"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Public Health)",
        "pi": "Preethi Bhattacharya",
        "department": "public health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates structural determinants of health disparities in cancer screening and treatment, with a focus on breast and cervical cancer in underserved populations.",
        "raw_keywords": ["public health", "health disparities", "cancer screening", "health equity", "social determinants"],
        "raw_skills": ["Stata", "R", "survey design", "qualitative methods"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pharmacology)",
        "pi": "Suresh Bhattacharya",
        "department": "pharmacology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies G protein-coupled receptor signaling and drug discovery for cardiovascular and metabolic diseases using structural pharmacology and high-throughput screening.",
        "raw_keywords": ["pharmacology", "GPCR", "drug discovery", "cardiovascular", "metabolism", "signaling"],
        "raw_skills": ["biochemistry", "FRET assays", "cell culture", "HTS"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Statistics)",
        "pi": "Anirban Bhattacharya",
        "department": "statistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops Bayesian statistical methods for high-dimensional biological data, including sparse regression models for GWAS and Bayesian nonparametrics for microbiome analysis.",
        "raw_keywords": ["statistics", "Bayesian", "GWAS", "microbiome", "high-dimensional", "data science"],
        "raw_skills": ["R", "Python", "Stan", "statistical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Internal Medicine)",
        "pi": "Susmita Bhattacharya",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Translational research on fibrosis and inflammation in chronic kidney disease and lupus nephritis, combining patient cohorts with mouse models and single-cell sequencing.",
        "raw_keywords": ["kidney disease", "fibrosis", "lupus", "inflammation", "single-cell", "translational"],
        "raw_skills": ["single-cell RNA-seq", "flow cytometry", "mouse models", "patient cohorts"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Environmental Health)",
        "pi": "Ritu Bhattacharya",
        "department": "environmental health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the effects of environmental exposures including air pollution and PFAS on epigenetic regulation and cancer risk, using epidemiological cohorts and mechanistic cell studies.",
        "raw_keywords": ["environmental health", "epigenetics", "PFAS", "air pollution", "cancer", "exposomics"],
        "raw_skills": ["epigenomics", "cell culture", "R", "epidemiology"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Psychology)",
        "pi": "Deepika Bhattacharya",
        "department": "psychology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses neuroimaging and computational modeling to study decision-making and reward processing in adolescents, with implications for addiction and mental health interventions.",
        "raw_keywords": ["psychology", "neuroimaging", "fMRI", "decision-making", "reward", "adolescence"],
        "raw_skills": ["fMRI", "MATLAB", "Python", "behavioral experiments"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Biostatistics)",
        "pi": "Nilanjana Bhattacharya",
        "department": "biostatistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops survival analysis and causal inference methods for clinical trials and observational studies, with applications in oncology and cardiovascular medicine.",
        "raw_keywords": ["biostatistics", "survival analysis", "causal inference", "clinical trials", "oncology"],
        "raw_skills": ["R", "SAS", "causal inference", "statistical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Aging)",
        "pi": "Samrat Bhattacharya",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the molecular hallmarks of aging including cellular senescence, mitochondrial dysfunction, and proteostasis collapse, seeking interventions to extend healthspan.",
        "raw_keywords": ["aging", "longevity", "senescence", "mitochondria", "proteostasis", "healthspan", "geroscience"],
        "raw_skills": ["cell culture", "mass spectrometry", "mouse models", "western blot"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
]


def main():
    out = {"labs": LABS}
    OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {len(LABS)} labs → {OUT}")
    print("Next: python tag_labs.py")


if __name__ == "__main__":
    main()
