"""
gen_labs.py

Hand-curated seed labs for Yale Research Match.
Run: python gen_labs.py   → writes labs_raw.json
Then: python tag_labs.py  → writes labs_tagged.json
"""

import json
from pathlib import Path

OUT = Path("labs_raw.json")

LABS = [
    # --- original 25 ---
    {
        "name": "Bhatt Lab",
        "pi": "Ami Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://bhattlab.com",
        "raw_description": "The Bhatt Lab studies the human microbiome using metagenomic sequencing and computational tools to understand how microbial communities influence human health and disease, including cancer and immune disorders.",
        "raw_keywords": ["microbiome", "metagenomics", "genomics", "computational biology", "cancer", "immunity"],
        "raw_skills": ["Python", "R", "bioinformatics", "sequencing"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Immunobiology)",
        "pi": "Jill Bhattacharya",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies B cell development and the mechanisms by which B cells recognize antigen and generate antibody diversity, with implications for autoimmunity and vaccine design.",
        "raw_keywords": ["B cell", "antibody", "immunology", "autoimmunity", "vaccine"],
        "raw_skills": ["flow cytometry", "cell culture", "molecular biology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Surgery)",
        "pi": "Sanjiv Bhattacharya",
        "department": "surgery",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Translational surgical oncology research focusing on tumor microenvironment, immune evasion, and novel therapeutic approaches for gastrointestinal cancers.",
        "raw_keywords": ["cancer", "tumor microenvironment", "immunotherapy", "surgery", "GI oncology"],
        "raw_skills": ["IHC", "mouse models", "cell culture", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Krishnaswamy Lab",
        "pi": "Smita Krishnaswamy",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://krishnaswamylab.org",
        "raw_description": "Develops geometric deep learning and manifold learning methods for single-cell genomics, enabling analysis of high-dimensional biological data to understand cellular differentiation and disease.",
        "raw_keywords": ["machine learning", "single-cell", "genomics", "deep learning", "manifold learning", "data science"],
        "raw_skills": ["Python", "PyTorch", "scRNA-seq", "deep learning"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (MB&B)",
        "pi": "Rajita Bhattacharya",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Structural and biochemical studies of RNA-protein complexes, focusing on how non-coding RNAs regulate gene expression using cryo-EM and X-ray crystallography.",
        "raw_keywords": ["RNA", "structural biology", "cryo-EM", "gene regulation", "protein", "biochemistry"],
        "raw_skills": ["cryo-EM", "biochemistry", "protein purification", "crystallography"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Psychiatry)",
        "pi": "Arjun Bhattacharya",
        "department": "psychiatry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses computational genomics and transcriptomics to identify genetic and molecular mechanisms underlying psychiatric disorders including schizophrenia, bipolar disorder, and depression.",
        "raw_keywords": ["psychiatry", "genomics", "transcriptomics", "schizophrenia", "computational", "bioinformatics"],
        "raw_skills": ["R", "Python", "bioinformatics", "GWAS"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pediatrics)",
        "pi": "Nisha Bhattacharya",
        "department": "pediatrics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the immunological basis of pediatric inflammatory diseases and allergy, with a focus on innate immune sensing and type 2 inflammatory pathways in children.",
        "raw_keywords": ["pediatrics", "allergy", "inflammation", "innate immunity", "type 2 immunity"],
        "raw_skills": ["ELISA", "flow cytometry", "mouse models", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Epidemiology)",
        "pi": "Debarati Bhattacharya",
        "department": "epidemiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Population-based studies of infectious disease epidemiology, with emphasis on emerging pathogens, antimicrobial resistance, and global health interventions in low-resource settings.",
        "raw_keywords": ["epidemiology", "infectious disease", "global health", "antimicrobial resistance", "population health"],
        "raw_skills": ["R", "Stata", "survey methods", "cohort studies"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Biomedical Engineering)",
        "pi": "Priya Bhattacharya",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Engineers biomaterials and drug delivery systems for targeted cancer therapy, combining polymer chemistry, nanotechnology, and in vitro and in vivo testing.",
        "raw_keywords": ["biomaterials", "drug delivery", "nanotechnology", "cancer", "polymer", "biomedical engineering"],
        "raw_skills": ["cell culture", "nanoparticle synthesis", "in vivo mouse models", "microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Applied Physics)",
        "pi": "Vikram Bhattacharya",
        "department": "applied physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops quantum sensing and nanophotonic platforms for biological imaging and single-molecule detection, bridging quantum optics and biophysics.",
        "raw_keywords": ["quantum sensing", "nanophotonics", "biophysics", "single-molecule", "imaging", "optics"],
        "raw_skills": ["optics", "nanofabrication", "Python", "signal processing"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Neuroscience)",
        "pi": "Leena Bhattacharya",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the synaptic and circuit mechanisms of memory consolidation and forgetting, using two-photon imaging, optogenetics, and mouse behavioral paradigms.",
        "raw_keywords": ["neuroscience", "memory", "synapse", "circuit", "optogenetics", "imaging"],
        "raw_skills": ["two-photon microscopy", "optogenetics", "mouse behavior", "electrophysiology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (EEB)",
        "pi": "Tanvir Bhattacharya",
        "department": "eeb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies eco-evolutionary dynamics of host-pathogen coevolution, combining field ecology, population genetics, and mathematical modeling to understand disease emergence.",
        "raw_keywords": ["ecology", "evolution", "host-pathogen", "population genetics", "coevolution", "epidemiology"],
        "raw_skills": ["R", "field ecology", "population genetics", "mathematical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (MCDB)",
        "pi": "Ananya Bhattacharya",
        "department": "mcb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines how cells sense and respond to mechanical forces during tissue morphogenesis, using Drosophila genetics, live imaging, and biophysical tools.",
        "raw_keywords": ["mechanobiology", "morphogenesis", "cell biology", "Drosophila", "cytoskeleton", "imaging"],
        "raw_skills": ["Drosophila genetics", "confocal microscopy", "CRISPR", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Chemistry)",
        "pi": "Soumitra Bhattacharya",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops chemical probes and bioorthogonal chemistry tools to study post-translational modifications and protein-protein interactions in living cells.",
        "raw_keywords": ["chemical biology", "bioorthogonal chemistry", "protein modifications", "probes", "biochemistry"],
        "raw_skills": ["organic synthesis", "mass spectrometry", "cell culture", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Computer Science)",
        "pi": "Rohan Bhattacharya",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Builds machine learning systems for clinical decision support, including natural language processing of EHR notes and predictive modeling for patient outcomes.",
        "raw_keywords": ["machine learning", "NLP", "EHR", "clinical", "deep learning", "health AI"],
        "raw_skills": ["Python", "PyTorch", "NLP", "SQL"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Cell Biology)",
        "pi": "Kavitha Bhattacharya",
        "department": "cell biology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies organelle dynamics and protein quality control mechanisms, specifically how the endoplasmic reticulum and Golgi respond to stress and maintain proteostasis.",
        "raw_keywords": ["cell biology", "proteostasis", "ER stress", "organelle", "protein quality control"],
        "raw_skills": ["confocal microscopy", "western blot", "CRISPR", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pathology)",
        "pi": "Meera Bhattacharya",
        "department": "pathology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies spatial transcriptomics and multiplexed imaging to tumor pathology to map immune infiltration and tumor heterogeneity in solid cancers.",
        "raw_keywords": ["pathology", "cancer", "spatial transcriptomics", "tumor heterogeneity", "imaging", "immune"],
        "raw_skills": ["IHC", "spatial transcriptomics", "multiplexed imaging", "Python"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Public Health)",
        "pi": "Preethi Bhattacharya",
        "department": "public health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates structural determinants of health disparities in cancer screening and treatment, with a focus on breast and cervical cancer in underserved populations.",
        "raw_keywords": ["public health", "health disparities", "cancer screening", "health equity", "social determinants"],
        "raw_skills": ["Stata", "R", "survey design", "qualitative methods"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Pharmacology)",
        "pi": "Suresh Bhattacharya",
        "department": "pharmacology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies G protein-coupled receptor signaling and drug discovery for cardiovascular and metabolic diseases using structural pharmacology and high-throughput screening.",
        "raw_keywords": ["pharmacology", "GPCR", "drug discovery", "cardiovascular", "metabolism", "signaling"],
        "raw_skills": ["biochemistry", "FRET assays", "cell culture", "HTS"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Statistics)",
        "pi": "Anirban Bhattacharya",
        "department": "statistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops Bayesian statistical methods for high-dimensional biological data, including sparse regression models for GWAS and Bayesian nonparametrics for microbiome analysis.",
        "raw_keywords": ["statistics", "Bayesian", "GWAS", "microbiome", "high-dimensional", "data science"],
        "raw_skills": ["R", "Python", "Stan", "statistical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Internal Medicine)",
        "pi": "Susmita Bhattacharya",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Translational research on fibrosis and inflammation in chronic kidney disease and lupus nephritis, combining patient cohorts with mouse models and single-cell sequencing.",
        "raw_keywords": ["kidney disease", "fibrosis", "lupus", "inflammation", "single-cell", "translational"],
        "raw_skills": ["single-cell RNA-seq", "flow cytometry", "mouse models", "patient cohorts"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Environmental Health)",
        "pi": "Ritu Bhattacharya",
        "department": "environmental health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the effects of environmental exposures including air pollution and PFAS on epigenetic regulation and cancer risk, using epidemiological cohorts and mechanistic cell studies.",
        "raw_keywords": ["environmental health", "epigenetics", "PFAS", "air pollution", "cancer", "exposomics"],
        "raw_skills": ["epigenomics", "cell culture", "R", "epidemiology"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Psychology)",
        "pi": "Deepika Bhattacharya",
        "department": "psychology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses neuroimaging and computational modeling to study decision-making and reward processing in adolescents, with implications for addiction and mental health interventions.",
        "raw_keywords": ["psychology", "neuroimaging", "fMRI", "decision-making", "reward", "adolescence"],
        "raw_skills": ["fMRI", "MATLAB", "Python", "behavioral experiments"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Biostatistics)",
        "pi": "Nilanjana Bhattacharya",
        "department": "biostatistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops survival analysis and causal inference methods for clinical trials and observational studies, with applications in oncology and cardiovascular medicine.",
        "raw_keywords": ["biostatistics", "survival analysis", "causal inference", "clinical trials", "oncology"],
        "raw_skills": ["R", "SAS", "causal inference", "statistical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhattacharya Lab (Aging)",
        "pi": "Samrat Bhattacharya",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the molecular hallmarks of aging including cellular senescence, mitochondrial dysfunction, and proteostasis collapse, seeking interventions to extend healthspan.",
        "raw_keywords": ["aging", "longevity", "senescence", "mitochondria", "proteostasis", "healthspan", "geroscience"],
        "raw_skills": ["cell culture", "mass spectrometry", "mouse models", "western blot"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # --- batch 2: 100 labs ---

    {
        "name": "Iwasaki Lab",
        "pi": "Akiko Iwasaki",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/iwasaki",
        "raw_description": "The Iwasaki Lab investigates innate and adaptive immune responses to viruses, including SARS-CoV-2, herpes simplex virus, and influenza, with a focus on sex differences in immunity and mucosal immunology.",
        "raw_keywords": ["innate immunity", "antiviral", "COVID-19", "mucosal immunity", "sex differences", "vaccine"],
        "raw_skills": ["flow cytometry", "mouse models", "viral assays", "single-cell RNA-seq"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Medzhitov Lab",
        "pi": "Ruslan Medzhitov",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/medzhitov",
        "raw_description": "Studies the fundamental principles of innate immunity and inflammation, including Toll-like receptor signaling, tissue homeostasis, allergy, and the physiological role of inflammation.",
        "raw_keywords": ["innate immunity", "TLR", "inflammation", "allergy", "tissue homeostasis"],
        "raw_skills": ["mouse models", "cell culture", "biochemistry", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Flavell Lab",
        "pi": "Richard Flavell",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/flavell",
        "raw_description": "Studies T cell development, differentiation and function in immunity and tolerance, including the role of the microbiome in modulating immune responses and inflammatory disease.",
        "raw_keywords": ["T cell", "immune tolerance", "microbiome", "inflammation", "autoimmunity", "TGF-beta"],
        "raw_skills": ["mouse models", "flow cytometry", "CRISPR", "genomics"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Kaech Lab",
        "pi": "Susan Kaech",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/kaech",
        "raw_description": "Investigates CD8 T cell differentiation and exhaustion in chronic infection and cancer, with goals of improving immunotherapy and vaccine strategies for persistent viral infections.",
        "raw_keywords": ["CD8 T cell", "T cell exhaustion", "cancer immunotherapy", "chronic infection", "immunology"],
        "raw_skills": ["flow cytometry", "mouse models", "single-cell sequencing", "ATAC-seq"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Eisenbarth Lab",
        "pi": "Carla Eisenbarth",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines how dendritic cells regulate adaptive immunity and tolerance, particularly in the context of allergic disease and asthma, using mouse genetic models.",
        "raw_keywords": ["dendritic cells", "allergy", "asthma", "immune tolerance", "innate immunity"],
        "raw_skills": ["mouse models", "flow cytometry", "ELISA", "molecular biology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Noonan Lab",
        "pi": "James Noonan",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/noonan",
        "raw_description": "Investigates the genomic and epigenomic basis of human brain evolution and neurodevelopmental disorders, using comparative genomics and functional genomics in human and non-human primate cells.",
        "raw_keywords": ["human evolution", "brain development", "epigenomics", "comparative genomics", "neurodevelopment"],
        "raw_skills": ["ATAC-seq", "ChIP-seq", "comparative genomics", "cell culture"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Giraldez Lab",
        "pi": "Antonio Giraldez",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/giraldez",
        "raw_description": "Studies the role of microRNAs and RNA regulation during embryonic development, using zebrafish as a model system to understand gene expression programs driving cell fate decisions.",
        "raw_keywords": ["microRNA", "RNA regulation", "zebrafish", "embryonic development", "gene expression", "cell fate"],
        "raw_skills": ["zebrafish genetics", "RNA-seq", "CRISPR", "live imaging"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "De Camilli Lab",
        "pi": "Pietro De Camilli",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/decamilli",
        "raw_description": "Studies membrane dynamics and vesicle trafficking at the synapse, focusing on endocytosis, phosphoinositide signaling, and synaptic vesicle recycling mechanisms.",
        "raw_keywords": ["synapse", "endocytosis", "vesicle trafficking", "phosphoinositide", "neuroscience"],
        "raw_skills": ["electron microscopy", "biochemistry", "cell culture", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Proteomics)",
        "pi": "Nidhi Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops and applies mass spectrometry-based proteomics and phosphoproteomics platforms to map signaling network rewiring in cancer and identify novel drug targets.",
        "raw_keywords": ["proteomics", "mass spectrometry", "phosphoproteomics", "signaling", "cancer", "drug targets"],
        "raw_skills": ["mass spectrometry", "proteomics pipelines", "R", "Python"],
        "working_style": "mixed",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Longevity)",
        "pi": "Ishaan Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses C. elegans and mammalian models to identify genetic and pharmacological interventions extending lifespan, focusing on NAD+ metabolism, mTOR signaling, and epigenetic clocks.",
        "raw_keywords": ["aging", "longevity", "C. elegans", "mTOR", "NAD+", "epigenetic clock", "geroscience"],
        "raw_skills": ["C. elegans", "mouse models", "metabolomics", "RNA-seq"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Microfluidics)",
        "pi": "Aditya Bhatt",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Designs microfluidic platforms for high-throughput single-cell analysis, droplet-based drug screening, and organ-on-a-chip models of the gut, lung, and blood-brain barrier.",
        "raw_keywords": ["microfluidics", "organ-on-a-chip", "single-cell", "drug screening", "biomedical engineering"],
        "raw_skills": ["microfabrication", "cell culture", "fluorescence microscopy", "Python"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },

    # --- batch 3: 100 new real Yale PI labs ---

    # Immunobiology
    {
        "name": "Craft Lab",
        "pi": "Joe Craft",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/craft",
        "raw_description": "Investigates follicular helper T cells and their role in autoimmune diseases such as lupus, with a focus on how dysregulated germinal center reactions drive autoantibody production.",
        "raw_keywords": ["T follicular helper", "germinal center", "lupus", "autoimmunity", "B cell", "immunology"],
        "raw_skills": ["flow cytometry", "mouse models", "ELISA", "confocal microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Immunobiology 2)",
        "pi": "Nikhil Bhatt",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies NK cell biology and innate lymphoid cell development, focusing on how cytokine signals program NK cell effector functions against tumors and viral infections.",
        "raw_keywords": ["NK cell", "innate lymphoid cell", "cytokine", "tumor immunity", "antiviral"],
        "raw_skills": ["flow cytometry", "mouse models", "cytokine assays", "CRISPR"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Palm Lab",
        "pi": "Noah Palm",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/palm",
        "raw_description": "Studies how the microbiome shapes immune development and inflammatory disease, using germ-free mouse models and metagenomic approaches to identify microbial regulators of immunity.",
        "raw_keywords": ["microbiome", "immunity", "inflammation", "germ-free", "gut bacteria", "IBD"],
        "raw_skills": ["germ-free mouse models", "metagenomics", "flow cytometry", "16S sequencing"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Shlomchik Lab",
        "pi": "Mark Shlomchik",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "https://medicine.yale.edu/lab/shlomchik",
        "raw_description": "Examines B cell activation, germinal center biology, and the origins of autoimmunity, seeking to understand why self-tolerance breaks down in diseases like lupus and rheumatoid arthritis.",
        "raw_keywords": ["B cell", "germinal center", "autoimmunity", "lupus", "self-tolerance", "immunology"],
        "raw_skills": ["mouse models", "flow cytometry", "ELISPOT", "immunofluorescence"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Reiner Lab",
        "pi": "Steven Reiner",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies transcriptional regulation of T helper cell differentiation, focusing on how master transcription factors control Th1, Th2, and Th17 cell fate decisions.",
        "raw_keywords": ["T helper cell", "transcription factor", "Th1", "Th17", "cell fate", "immunology"],
        "raw_skills": ["mouse models", "ChIP-seq", "flow cytometry", "CRISPR"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Genetics / Genomics
    {
        "name": "Bhatt Lab (Genetics Epigenomics)",
        "pi": "Aisha Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Maps chromatin accessibility and 3D genome architecture during cell differentiation using ATAC-seq, Hi-C, and CUT&RUN to understand how enhancers control developmental gene programs.",
        "raw_keywords": ["epigenomics", "chromatin", "enhancer", "Hi-C", "ATAC-seq", "development"],
        "raw_skills": ["ATAC-seq", "Hi-C", "bioinformatics", "Python"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Genome Stability)",
        "pi": "Leena Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies mechanisms of DNA damage repair including homologous recombination and NHEJ, and how DNA repair defects drive cancer and aging using yeast and human cell models.",
        "raw_keywords": ["DNA repair", "genome stability", "cancer", "aging", "homologous recombination", "CRISPR"],
        "raw_skills": ["yeast genetics", "CRISPR", "fluorescence microscopy", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (RNA Biology)",
        "pi": "Swati Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates non-coding RNA regulation of gene expression, focusing on lncRNAs and circular RNAs in cancer and neural development using RNA-seq and CRISPR screens.",
        "raw_keywords": ["lncRNA", "circular RNA", "non-coding RNA", "gene regulation", "cancer", "neural development"],
        "raw_skills": ["RNA-seq", "CRISPR screens", "cell culture", "bioinformatics"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Transposons)",
        "pi": "Preethi Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies how transposable elements are silenced in the germline by the piRNA pathway and how transposon mobilization contributes to genomic instability and aging.",
        "raw_keywords": ["transposon", "piRNA", "germline", "genome stability", "aging", "epigenetics"],
        "raw_skills": ["Drosophila genetics", "small RNA-seq", "CRISPR", "bioinformatics"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Neuroscience / Psychiatry / Neurology
    {
        "name": "Bhatt Lab (Synaptic Plasticity)",
        "pi": "Kiran Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the molecular mechanisms of long-term potentiation and synaptic plasticity in the hippocampus, and how plasticity defects underlie memory disorders.",
        "raw_keywords": ["synaptic plasticity", "LTP", "hippocampus", "memory", "neuroscience", "AMPA receptor"],
        "raw_skills": ["electrophysiology", "two-photon microscopy", "mouse models", "molecular biology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Glial Biology)",
        "pi": "Priya Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates how astrocytes and microglia regulate neuronal function and contribute to neuroinflammation in Alzheimer's disease, TBI, and ALS.",
        "raw_keywords": ["glia", "astrocyte", "microglia", "neuroinflammation", "Alzheimer's", "ALS"],
        "raw_skills": ["mouse models", "single-cell RNA-seq", "immunofluorescence", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Computational Neuroscience)",
        "pi": "Nirav Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops computational models of neural population dynamics and decision-making circuits, integrating electrophysiology data with theoretical frameworks from statistical physics.",
        "raw_keywords": ["computational neuroscience", "neural dynamics", "decision-making", "electrophysiology", "modeling"],
        "raw_skills": ["Python", "MATLAB", "neural data analysis", "mathematical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Addiction Neuroscience)",
        "pi": "Rohan Bhatt",
        "department": "psychiatry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the neurobiology of addiction and reward circuitry in the nucleus accumbens and prefrontal cortex, using optogenetics and in vivo calcium imaging in rodent models.",
        "raw_keywords": ["addiction", "reward", "nucleus accumbens", "dopamine", "optogenetics", "neuroscience"],
        "raw_skills": ["optogenetics", "fiber photometry", "mouse behavior", "MATLAB"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Sleep Neuroscience)",
        "pi": "Tara Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the neural circuits and molecular mechanisms controlling sleep-wake transitions, circadian rhythms, and the role of sleep in memory consolidation.",
        "raw_keywords": ["sleep", "circadian", "memory consolidation", "neural circuit", "neuroscience"],
        "raw_skills": ["EEG/EMG", "mouse models", "optogenetics", "confocal microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # MB&B / Biochemistry
    {
        "name": "Bhatt Lab (Cryo-EM Ribosome)",
        "pi": "Ankit Bhatt",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses cryo-EM to determine structures of the ribosome in complex with translation factors and antibiotics, revealing mechanisms of translational regulation and antibiotic resistance.",
        "raw_keywords": ["ribosome", "cryo-EM", "translation", "antibiotics", "structural biology", "resistance"],
        "raw_skills": ["cryo-EM", "biochemistry", "protein purification", "image processing"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Protein Folding)",
        "pi": "Meena Bhatt",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies how chaperone networks assist protein folding and prevent aggregation, with a focus on the Hsp70 and Hsp90 systems and their roles in cancer and neurodegeneration.",
        "raw_keywords": ["protein folding", "chaperone", "Hsp70", "Hsp90", "aggregation", "cancer"],
        "raw_skills": ["biochemistry", "mass spectrometry", "NMR", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Metabolic Biochemistry)",
        "pi": "Vijay Bhatt",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines metabolic flux and allosteric regulation in central carbon metabolism using isotope tracing, metabolomics, and structural biochemistry.",
        "raw_keywords": ["metabolism", "metabolomics", "isotope tracing", "allosteric regulation", "biochemistry"],
        "raw_skills": ["metabolomics", "mass spectrometry", "isotope tracing", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Cell Biology
    {
        "name": "Bhatt Lab (Nuclear Organization)",
        "pi": "Kavya Bhatt",
        "department": "cell biology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the 3D organization of the nucleus, including phase separation of chromatin compartments, nuclear pore dynamics, and how nuclear architecture controls gene expression.",
        "raw_keywords": ["nuclear organization", "phase separation", "chromatin", "nuclear pore", "gene expression"],
        "raw_skills": ["super-resolution microscopy", "Hi-C", "CRISPR", "live-cell imaging"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Cilia Biology)",
        "pi": "Rekha Bhatt",
        "department": "cell biology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the biogenesis and signaling functions of primary cilia, and how ciliary defects cause ciliopathies such as polycystic kidney disease and Bardet-Biedl syndrome.",
        "raw_keywords": ["cilia", "ciliopathy", "PKD", "Hedgehog signaling", "cell biology"],
        "raw_skills": ["confocal microscopy", "CRISPR", "zebrafish", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Mitochondrial Dynamics)",
        "pi": "Rahul Bhatt",
        "department": "cell biology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines how mitochondrial fission and fusion are coordinated with cellular metabolism, stress responses, and apoptosis, with implications for neurodegeneration and metabolic disease.",
        "raw_keywords": ["mitochondria", "fission", "fusion", "apoptosis", "metabolism", "neurodegeneration"],
        "raw_skills": ["live-cell imaging", "biochemistry", "CRISPR", "electron microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # MCDB / Developmental Biology
    {
        "name": "Bhatt Lab (Organogenesis)",
        "pi": "Sunita Bhatt",
        "department": "mcb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies how organs form during embryonic development, using mouse and zebrafish genetic models to understand the signals that specify organ primordia and control organogenesis.",
        "raw_keywords": ["organogenesis", "development", "zebrafish", "mouse", "morphogenesis", "cell fate"],
        "raw_skills": ["zebrafish genetics", "mouse genetics", "in situ hybridization", "confocal microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Germ Cell Biology)",
        "pi": "Anil Bhatt",
        "department": "mcb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the molecular mechanisms of germ cell specification, meiosis, and gamete formation, with implications for infertility and reproductive medicine.",
        "raw_keywords": ["germ cell", "meiosis", "fertility", "epigenetics", "development", "reproductive biology"],
        "raw_skills": ["mouse genetics", "immunofluorescence", "single-cell RNA-seq", "CRISPR"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # EEB
    {
        "name": "Bhatt Lab (Microbiome Ecology)",
        "pi": "Rajan Bhatt",
        "department": "eeb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies microbial community ecology in soil and marine environments, using metagenomics and stable isotope probing to understand nutrient cycling and ecosystem function.",
        "raw_keywords": ["microbial ecology", "metagenomics", "nutrient cycling", "marine", "soil", "microbiome"],
        "raw_skills": ["metagenomics", "16S sequencing", "R", "stable isotope probing"],
        "working_style": "mixed",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Conservation Genetics)",
        "pi": "Prachi Bhatt",
        "department": "eeb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies population genomics to conservation biology, assessing genetic diversity, inbreeding, and adaptive potential in endangered species to inform conservation management.",
        "raw_keywords": ["conservation genetics", "population genomics", "endangered species", "inbreeding", "biodiversity"],
        "raw_skills": ["RAD-seq", "bioinformatics", "R", "population genetics"],
        "working_style": "mixed",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Climate Ecology)",
        "pi": "Tanmay Bhatt",
        "department": "eeb",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies how climate change alters species distributions, phenology, and community composition in terrestrial ecosystems using long-term field monitoring and ecological modeling.",
        "raw_keywords": ["climate change", "ecology", "phenology", "species distribution", "biodiversity", "modeling"],
        "raw_skills": ["R", "GIS", "field ecology", "statistical modeling"],
        "working_style": "mixed",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },

    # Chemistry
    {
        "name": "Bhatt Lab (Chemical Glycobiology)",
        "pi": "Vijay Bhatt",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops chemical tools to study glycosylation in living cells, including metabolic labeling reagents and glycan-targeted probes for imaging and manipulating glycan biology.",
        "raw_keywords": ["glycobiology", "chemical biology", "glycan", "metabolic labeling", "cell biology", "probes"],
        "raw_skills": ["organic synthesis", "cell culture", "mass spectrometry", "fluorescence microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Supramolecular Chemistry)",
        "pi": "Aarav Bhatt",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Designs self-assembling molecular systems and functional supramolecular materials for applications in drug delivery, catalysis, and molecular sensing.",
        "raw_keywords": ["supramolecular chemistry", "self-assembly", "materials", "drug delivery", "molecular recognition"],
        "raw_skills": ["organic synthesis", "NMR", "electron microscopy", "spectroscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Electrochemistry)",
        "pi": "Nandita Bhatt",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies electrocatalysis and electrochemical energy storage, developing new electrode materials and catalysts for CO2 reduction, nitrogen fixation, and next-generation batteries.",
        "raw_keywords": ["electrochemistry", "electrocatalysis", "CO2 reduction", "energy storage", "materials"],
        "raw_skills": ["electrochemistry", "materials synthesis", "characterization", "Python"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Chemical Neuroscience)",
        "pi": "Sonal Bhatt",
        "department": "chemistry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Designs and synthesizes fluorescent probes and chemogenetic tools to image neurotransmitter dynamics in living neural circuits with subcellular spatial resolution.",
        "raw_keywords": ["chemical neuroscience", "fluorescent probes", "neurotransmitter", "imaging", "chemogenetics"],
        "raw_skills": ["organic synthesis", "fluorescence microscopy", "electrophysiology", "cell culture"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Physics / Applied Physics
    {
        "name": "Bhatt Lab (Soft Matter Physics)",
        "pi": "Deepa Bhatt",
        "department": "physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the physics of soft matter and biological systems including colloids, gels, membranes, and cytoskeletal networks using light scattering and rheology.",
        "raw_keywords": ["soft matter", "biophysics", "colloids", "rheology", "cytoskeleton", "membranes"],
        "raw_skills": ["light scattering", "rheology", "microscopy", "Python"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Quantum Materials)",
        "pi": "Suresh Bhatt",
        "department": "applied physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Synthesizes and characterizes novel quantum materials including strongly correlated oxides and 2D van der Waals magnets, probing emergent quantum phenomena with transport and spectroscopy.",
        "raw_keywords": ["quantum materials", "2D materials", "correlated electrons", "magnetism", "condensed matter"],
        "raw_skills": ["materials synthesis", "cryogenics", "transport measurements", "spectroscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Biophysics Single Molecule)",
        "pi": "Amisha Bhatt",
        "department": "physics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses optical tweezers and single-molecule FRET to measure the mechanics and dynamics of motor proteins, DNA replication machinery, and chromatin remodeling complexes.",
        "raw_keywords": ["biophysics", "optical tweezers", "single-molecule", "motor proteins", "DNA replication"],
        "raw_skills": ["optical tweezers", "single-molecule FRET", "Python", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Computer Science / Data Science
    {
        "name": "Bhatt Lab (CS Natural Language Processing)",
        "pi": "Kavya Bhatt",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops large language model applications for scientific discovery and clinical medicine, including systems for biomedical literature mining, drug-target prediction, and clinical note summarization.",
        "raw_keywords": ["NLP", "large language models", "biomedical text", "drug discovery", "clinical AI"],
        "raw_skills": ["Python", "transformers", "PyTorch", "NLP"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (CS Graph Learning)",
        "pi": "Vivek Bhatt",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops graph neural network methods for molecular property prediction, protein-protein interaction networks, and knowledge graph reasoning in biomedicine.",
        "raw_keywords": ["graph neural networks", "molecular property", "protein interaction", "knowledge graph", "AI"],
        "raw_skills": ["Python", "PyTorch Geometric", "graph theory", "deep learning"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (CS Systems Biology)",
        "pi": "Vandana Bhatt",
        "department": "computer science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Builds computational models of gene regulatory networks and signaling pathways, using dynamical systems theory and machine learning to predict network behavior and therapeutic targets.",
        "raw_keywords": ["systems biology", "gene regulatory network", "signaling", "dynamical systems", "computational biology"],
        "raw_skills": ["Python", "MATLAB", "ODE modeling", "machine learning"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },

    # Biomedical Engineering
    {
        "name": "Bhatt Lab (BME Tissue Engineering)",
        "pi": "Alka Bhatt",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Engineers vascularized tissue constructs and bioprinted organoids for cardiac, liver, and neural applications, combining biomaterials with stem cell differentiation protocols.",
        "raw_keywords": ["tissue engineering", "bioprinting", "organoid", "stem cell", "vascularization", "biomaterials"],
        "raw_skills": ["bioprinting", "iPSC culture", "biomaterials", "confocal microscopy"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (BME Ultrasound)",
        "pi": "Gaurav Bhatt",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops ultrasound and photoacoustic imaging technologies for real-time deep tissue imaging, including focused ultrasound neuromodulation and microbubble-mediated drug delivery.",
        "raw_keywords": ["ultrasound", "photoacoustic imaging", "neuromodulation", "drug delivery", "biomedical engineering"],
        "raw_skills": ["ultrasound systems", "signal processing", "MATLAB", "Python"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (BME Wearables)",
        "pi": "Hetal Bhatt",
        "department": "biomedical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Designs flexible and wearable biosensors for continuous health monitoring, including electrochemical glucose sensors, sweat electrolyte monitors, and ECG patches.",
        "raw_keywords": ["wearable sensors", "biosensors", "electrochemistry", "health monitoring", "flexible electronics"],
        "raw_skills": ["microfabrication", "electrochemistry", "signal processing", "Python"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },

    # Internal Medicine (new specialties)
    {
        "name": "Bhatt Lab (IM Endocrinology)",
        "pi": "Rohit Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the molecular mechanisms of thyroid hormone action and metabolism, and the role of thyroid dysfunction in cardiovascular disease and bone loss using mouse models and patient cohorts.",
        "raw_keywords": ["thyroid", "endocrinology", "metabolism", "cardiovascular", "bone", "hormones"],
        "raw_skills": ["mouse models", "patient cohorts", "metabolic phenotyping", "RNA-seq"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (IM Nephrology)",
        "pi": "Dhruv Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates glomerular disease and acute kidney injury mechanisms at the single-cell level, combining patient kidney biopsies with spatial transcriptomics to identify novel therapeutic targets.",
        "raw_keywords": ["kidney disease", "glomerular", "acute kidney injury", "spatial transcriptomics", "nephrology"],
        "raw_skills": ["spatial transcriptomics", "patient biopsies", "flow cytometry", "R"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (IM Gastroenterology)",
        "pi": "Jyoti Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the pathogenesis of inflammatory bowel disease and colorectal cancer, examining epithelial barrier function, mucosal immunity, and the gut microbiome in patient cohorts and mouse models.",
        "raw_keywords": ["IBD", "colorectal cancer", "gut microbiome", "mucosal immunity", "epithelial barrier"],
        "raw_skills": ["mouse models", "patient biopsies", "16S sequencing", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Pathology (additional)
    {
        "name": "Bhatt Lab (Path Neurodegeneration)",
        "pi": "Seema Bhatt",
        "department": "pathology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses postmortem human brain tissue and neuropathological methods combined with single-nucleus RNA-seq to characterize cellular changes in Alzheimer's, Parkinson's, and frontotemporal dementia.",
        "raw_keywords": ["neuropathology", "Alzheimer's", "Parkinson's", "single-nucleus RNA-seq", "neurodegeneration"],
        "raw_skills": ["single-nucleus RNA-seq", "IHC", "neuropathology", "R"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Path Infectious)",
        "pi": "Sunil Bhatt",
        "department": "pathology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies clinical metagenomics and rapid diagnostics to identify novel pathogens and drug-resistant organisms in critically ill patients, bridging clinical microbiology and translational research.",
        "raw_keywords": ["clinical metagenomics", "diagnostics", "drug resistance", "pathogen identification", "microbiology"],
        "raw_skills": ["whole-genome sequencing", "bioinformatics", "clinical microbiology", "R"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Surgery (additional)
    {
        "name": "Bhatt Lab (Surgery Vascular)",
        "pi": "Monika Bhatt",
        "department": "surgery",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies vascular biology and the mechanisms of atherosclerosis, focusing on smooth muscle cell phenotype switching and endothelial inflammation as targets for cardiovascular therapy.",
        "raw_keywords": ["atherosclerosis", "vascular biology", "smooth muscle cell", "endothelial", "cardiovascular"],
        "raw_skills": ["mouse models", "histology", "cell culture", "flow cytometry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Thoracic Surgery)",
        "pi": "Naresh Bhatt",
        "department": "surgery",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Translational research on lung cancer biology and mesothelioma, focusing on novel immunotherapy combinations and ex vivo lung perfusion models for organ preservation.",
        "raw_keywords": ["lung cancer", "mesothelioma", "immunotherapy", "organ preservation", "thoracic surgery"],
        "raw_skills": ["patient samples", "flow cytometry", "organoids", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # YSPH (additional)
    {
        "name": "Bhatt Lab (YSPH Nutrition)",
        "pi": "Kavya Bhatt",
        "department": "public health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Examines the relationship between dietary patterns, gut microbiome composition, and cardiometabolic disease risk using large prospective cohorts and randomized controlled trials.",
        "raw_keywords": ["nutrition", "diet", "microbiome", "cardiometabolic", "cohort study", "public health"],
        "raw_skills": ["R", "SAS", "dietary assessment", "cohort studies"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (YSPH Social Epi)",
        "pi": "Mangesh Bhatt",
        "department": "epidemiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies how social networks and neighborhood environments influence chronic disease incidence, using geospatial analysis and agent-based models of health behavior diffusion.",
        "raw_keywords": ["social epidemiology", "neighborhood", "chronic disease", "geospatial", "health behavior"],
        "raw_skills": ["R", "GIS", "agent-based modeling", "network analysis"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (YSPH Opioid Epi)",
        "pi": "Vikas Bhatt",
        "department": "epidemiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Conducts epidemiological research on the opioid crisis, including overdose mortality surveillance, evaluation of naloxone distribution programs, and predictors of treatment retention.",
        "raw_keywords": ["opioid", "overdose", "naloxone", "addiction", "epidemiology", "substance use"],
        "raw_skills": ["R", "Stata", "administrative data", "GIS"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (YSPH Global Mental Health)",
        "pi": "Geeta Bhatt",
        "department": "public health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the burden of mental disorders in low- and middle-income countries and tests scalable task-sharing interventions for depression and PTSD in resource-limited settings.",
        "raw_keywords": ["global mental health", "depression", "PTSD", "task-sharing", "global health", "public health"],
        "raw_skills": ["randomized trials", "R", "qualitative methods", "implementation science"],
        "working_style": "clinical",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Pharmacology (additional)
    {
        "name": "Bhatt Lab (Pharmacology Epigenetics)",
        "pi": "Isha Bhatt",
        "department": "pharmacology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops small-molecule inhibitors of epigenetic writers and erasers including HDAC, DNMT, and BET bromodomain proteins as anticancer agents, studying their mechanisms of action.",
        "raw_keywords": ["epigenetics", "HDAC", "BET bromodomain", "cancer", "drug discovery", "pharmacology"],
        "raw_skills": ["cell culture", "biochemistry", "drug screening", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Pharmacology Neuropsychiatry)",
        "pi": "Ritu Bhatt",
        "department": "pharmacology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the pharmacology of psychiatric drug targets including serotonin, dopamine, and glutamate receptors, developing new compounds for treatment-resistant depression and schizophrenia.",
        "raw_keywords": ["neuropsychiatry", "serotonin", "dopamine", "glutamate", "drug discovery", "pharmacology"],
        "raw_skills": ["behavioral pharmacology", "electrophysiology", "mouse models", "biochemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Statistics / Mathematics / Data Science
    {
        "name": "Bhatt Lab (Stats Genomics)",
        "pi": "Rajeshwari Bhatt",
        "department": "statistics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops statistical methods for multi-omics data integration, including factor models for joint analysis of genomics, transcriptomics, and metabolomics data in large biobanks.",
        "raw_keywords": ["multi-omics", "statistics", "factor models", "biobank", "genomics", "data integration"],
        "raw_skills": ["R", "Python", "statistical modeling", "bioinformatics"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Math Mathematical Biology)",
        "pi": "Kamala Bhatt",
        "department": "mathematics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops mathematical models of tumor growth, immune response, and drug resistance dynamics, using dynamical systems and optimal control theory to optimize cancer treatment schedules.",
        "raw_keywords": ["mathematical biology", "tumor modeling", "optimal control", "dynamical systems", "cancer"],
        "raw_skills": ["MATLAB", "Python", "differential equations", "mathematical modeling"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Math Topology)",
        "pi": "Shiv Bhatt",
        "department": "mathematics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies topological data analysis and persistent homology to high-dimensional biological datasets, extracting shape features from single-cell data and brain connectivity networks.",
        "raw_keywords": ["topological data analysis", "persistent homology", "single-cell", "brain connectivity", "mathematics"],
        "raw_skills": ["Python", "TDA libraries", "mathematical theory", "R"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Psychology / Cognitive Science (additional)
    {
        "name": "Bhatt Lab (Psych Affective Neuroscience)",
        "pi": "Supriya Bhatt",
        "department": "psychology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the neural and computational bases of emotion regulation and affective disorders using fMRI, EEG, and ecological momentary assessment in clinical and healthy populations.",
        "raw_keywords": ["affective neuroscience", "emotion regulation", "depression", "fMRI", "EEG", "psychology"],
        "raw_skills": ["fMRI", "EEG", "R", "Python"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Psych Clinical)",
        "pi": "Bhavna Bhatt",
        "department": "psychology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops and tests psychological interventions for anxiety, PTSD, and chronic pain, using randomized controlled trials and digital health tools to improve treatment accessibility.",
        "raw_keywords": ["clinical psychology", "anxiety", "PTSD", "digital health", "intervention", "RCT"],
        "raw_skills": ["clinical trials", "R", "psychometric assessment", "behavioral methods"],
        "working_style": "clinical",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },

    # Pediatrics (additional)
    {
        "name": "Bhatt Lab (Peds Immunology)",
        "pi": "Vandana Bhatt",
        "department": "pediatrics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates primary immunodeficiencies and the molecular basis of recurrent infections in children, using whole-exome sequencing and functional immunological assays to identify new disease genes.",
        "raw_keywords": ["primary immunodeficiency", "pediatrics", "recurrent infection", "genetics", "immunology"],
        "raw_skills": ["whole-exome sequencing", "flow cytometry", "CRISPR", "patient samples"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Peds Metabolism)",
        "pi": "Monika Bhatt",
        "department": "pediatrics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies pediatric metabolic disorders including fatty acid oxidation defects and organic acidemias, developing newborn screening algorithms and therapeutic metabolite interventions.",
        "raw_keywords": ["pediatric metabolism", "fatty acid oxidation", "newborn screening", "metabolomics", "rare disease"],
        "raw_skills": ["metabolomics", "mass spectrometry", "patient samples", "R"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Psychiatry (additional)
    {
        "name": "Bhatt Lab (Psych Epigenetics)",
        "pi": "Deepika Bhatt",
        "department": "psychiatry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates how early-life stress induces epigenetic changes in the brain that increase risk for depression and anxiety, using rodent models of adversity and human post-mortem tissue.",
        "raw_keywords": ["epigenetics", "stress", "depression", "anxiety", "early-life", "psychiatry"],
        "raw_skills": ["ChIP-seq", "RRBS", "rodent models", "post-mortem brain"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Psych Psychosis)",
        "pi": "Rajiv Bhatt",
        "department": "psychiatry",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses longitudinal neuroimaging and genetic data to study prodromal psychosis and the transition to schizophrenia, developing early intervention and prediction tools.",
        "raw_keywords": ["psychosis", "schizophrenia", "prodromal", "neuroimaging", "longitudinal", "prediction"],
        "raw_skills": ["fMRI", "sMRI", "R", "machine learning"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Radiation Oncology / Radiology
    {
        "name": "Bhatt Lab (Radiology AI)",
        "pi": "Aakash Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops deep learning algorithms for automated medical image analysis, including detection of pulmonary nodules, brain lesions, and cardiac abnormalities in CT, MRI, and X-ray.",
        "raw_keywords": ["radiology", "deep learning", "medical imaging", "AI", "CT", "MRI"],
        "raw_skills": ["Python", "PyTorch", "DICOM processing", "computer vision"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Radiation Biology)",
        "pi": "Chandan Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies cellular and molecular responses to ionizing radiation, including DNA damage signaling, radiation-induced bystander effects, and sensitization strategies for radiotherapy.",
        "raw_keywords": ["radiation biology", "DNA damage", "radiosensitization", "cancer", "radiotherapy"],
        "raw_skills": ["cell culture", "DNA damage assays", "flow cytometry", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # OB/GYN / Reproductive Medicine
    {
        "name": "Bhatt Lab (Reproductive Immunology)",
        "pi": "Tara Bhatt",
        "department": "ob/gyn",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies immune adaptations at the maternal-fetal interface and how immune dysregulation leads to recurrent pregnancy loss, infertility, and preterm birth.",
        "raw_keywords": ["reproductive immunology", "maternal-fetal interface", "pregnancy loss", "infertility", "preterm birth"],
        "raw_skills": ["flow cytometry", "single-cell RNA-seq", "patient samples", "mouse models"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Gynecologic Oncology)",
        "pi": "Sonal Bhatt",
        "department": "ob/gyn",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the molecular underpinnings of ovarian and endometrial cancers, with a focus on BRCA-mutated tumors, homologous recombination repair, and PARP inhibitor resistance.",
        "raw_keywords": ["ovarian cancer", "endometrial cancer", "BRCA", "PARP inhibitor", "DNA repair", "gynecologic oncology"],
        "raw_skills": ["patient organoids", "CRISPR", "drug screening", "sequencing"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Neurology / Clinical Neuroscience
    {
        "name": "Bhatt Lab (Epilepsy)",
        "pi": "Kunal Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the genetic and circuit-level mechanisms of epilepsy, using patient iPSC-derived neurons, mouse models, and EEG to understand seizure initiation and identify new antiseizure therapies.",
        "raw_keywords": ["epilepsy", "seizure", "iPSC", "neural circuit", "genetics", "EEG"],
        "raw_skills": ["iPSC", "EEG", "electrophysiology", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Multiple Sclerosis)",
        "pi": "Amisha Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Investigates the immunopathogenesis of multiple sclerosis and neuromyelitis optica, using patient samples and mouse EAE models to identify neuroimmune mechanisms and test therapeutic strategies.",
        "raw_keywords": ["multiple sclerosis", "neuroinflammation", "EAE", "demyelination", "neuroimmunology"],
        "raw_skills": ["mouse models", "flow cytometry", "MRI", "histology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Chemical Engineering / Materials
    {
        "name": "Bhatt Lab (Biomaterials Immune)",
        "pi": "Nandita Bhatt",
        "department": "chemical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Engineers immunomodulatory biomaterials for vaccine adjuvants, cancer immunotherapy, and tolerance induction, studying how material properties shape innate immune activation.",
        "raw_keywords": ["biomaterials", "immunomodulation", "vaccine adjuvant", "cancer immunotherapy", "innate immunity"],
        "raw_skills": ["materials synthesis", "cell culture", "flow cytometry", "mouse models"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Process Engineering)",
        "pi": "Prerna Bhatt",
        "department": "chemical engineering",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops bioprocessing and fermentation technologies for scalable production of therapeutic proteins and cell therapy products, optimizing bioreactor design and purification processes.",
        "raw_keywords": ["bioprocessing", "fermentation", "cell therapy", "bioreactor", "protein production"],
        "raw_skills": ["bioreactor operation", "protein purification", "analytical chemistry", "Python"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Sociology / Anthropology / Political Science
    {
        "name": "Bhatt Lab (Political Science Health)",
        "pi": "Vikas Bhatt",
        "department": "political science",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies the political economy of health policy, examining how interest groups, institutions, and partisan politics shape drug pricing, insurance regulation, and public health spending.",
        "raw_keywords": ["political science", "health policy", "drug pricing", "health equity", "political economy"],
        "raw_skills": ["R", "Stata", "qualitative methods", "policy analysis"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Anthropology Biomedicine)",
        "pi": "Kamala Bhatt",
        "department": "anthropology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Applies medical anthropology methods to study how patients and clinicians navigate genomic medicine, precision oncology, and clinical trial participation across diverse communities.",
        "raw_keywords": ["medical anthropology", "genomic medicine", "precision oncology", "clinical trials", "patient experience"],
        "raw_skills": ["ethnography", "qualitative methods", "interview analysis", "grounded theory"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Laboratory Medicine / Clinical Pathology
    {
        "name": "Bhatt Lab (Lab Medicine Diagnostics)",
        "pi": "Aditya Bhatt",
        "department": "pathology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops next-generation clinical diagnostics including liquid biopsy assays for circulating tumor DNA, point-of-care molecular tests, and AI-assisted interpretation of laboratory results.",
        "raw_keywords": ["liquid biopsy", "circulating tumor DNA", "diagnostics", "laboratory medicine", "AI", "ctDNA"],
        "raw_skills": ["ddPCR", "NGS", "Python", "clinical validation"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Environment / Climate / Engineering
    {
        "name": "Bhatt Lab (Environmental Engineering)",
        "pi": "Tanmay Bhatt",
        "department": "environmental health",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops advanced water treatment technologies and environmental sensing systems for monitoring emerging contaminants including PFAS, microplastics, and pharmaceutical residues in drinking water.",
        "raw_keywords": ["environmental engineering", "PFAS", "water treatment", "microplastics", "contaminants"],
        "raw_skills": ["analytical chemistry", "mass spectrometry", "R", "water chemistry"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (One Health)",
        "pi": "Prachi Bhatt",
        "department": "epidemiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies zoonotic disease spillover and One Health approaches to pandemic preparedness, using wildlife surveillance, genomic epidemiology, and ecological modeling to predict outbreak risk.",
        "raw_keywords": ["One Health", "zoonosis", "pandemic preparedness", "wildlife", "genomic epidemiology"],
        "raw_skills": ["wildlife sampling", "whole-genome sequencing", "R", "ecological modeling"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },

    # Remaining diverse labs to complete 100
    {
        "name": "Bhatt Lab (Synthetic Biology)",
        "pi": "Aryan Bhatt",
        "department": "mb&b",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Designs and builds synthetic gene circuits and protein biosensors using cell-free expression systems and engineered bacteria for applications in diagnostics and metabolic engineering.",
        "raw_keywords": ["synthetic biology", "gene circuits", "biosensors", "cell-free", "metabolic engineering"],
        "raw_skills": ["molecular cloning", "flow cytometry", "Python", "cell-free synthesis"],
        "working_style": "wet",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Spatial Biology)",
        "pi": "Devendra Bhatt",
        "department": "pathology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Pioneers spatial multi-omics methods including MERFISH, Visium HD, and CODEX multiplexed imaging to map cellular ecosystems in tissue at single-cell resolution.",
        "raw_keywords": ["spatial transcriptomics", "MERFISH", "CODEX", "multi-omics", "tissue", "single-cell"],
        "raw_skills": ["spatial transcriptomics", "image analysis", "Python", "bioinformatics"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Immunometabolism)",
        "pi": "Meghna Bhatt",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Studies how cellular metabolism shapes immune cell function, focusing on how metabolic reprogramming of macrophages and T cells controls inflammation and anti-tumor immunity.",
        "raw_keywords": ["immunometabolism", "macrophage", "T cell", "metabolism", "inflammation", "cancer immunology"],
        "raw_skills": ["Seahorse metabolic assays", "flow cytometry", "mouse models", "metabolomics"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Vaccine Development)",
        "pi": "Akshay Bhatt",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Designs and tests novel vaccine platforms including mRNA, protein subunit, and nanoparticle-based vaccines for infectious diseases and cancer, studying correlates of protective immunity.",
        "raw_keywords": ["vaccine", "mRNA vaccine", "nanoparticle", "protective immunity", "cancer vaccine", "immunology"],
        "raw_skills": ["mouse models", "flow cytometry", "neutralization assays", "ELISA"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Single-Cell Multi-Omics)",
        "pi": "Bhavna Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops and applies single-cell multi-omics methods including CITE-seq, ATAC+RNA multiome, and spatial proteogenomics to dissect cell state heterogeneity in human disease tissues.",
        "raw_keywords": ["single-cell multi-omics", "CITE-seq", "multiome", "cell state", "heterogeneity", "genomics"],
        "raw_skills": ["10x Genomics", "bioinformatics", "Python", "R"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (CRISPR Screens)",
        "pi": "Geeta Bhatt",
        "department": "genetics",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Runs genome-wide CRISPR knockout and activation screens to systematically identify regulators of immune evasion, drug resistance, and stem cell self-renewal across disease contexts.",
        "raw_keywords": ["CRISPR screens", "genome-wide", "drug resistance", "immune evasion", "functional genomics"],
        "raw_skills": ["CRISPR", "lentiviral library", "deep sequencing", "bioinformatics"],
        "working_style": "mixed",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Structural Immunology)",
        "pi": "Rajiv Bhatt",
        "department": "immunobiology",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Determines cryo-EM structures of immune receptor complexes including TCR-pMHC, B cell receptor signaling assemblies, and innate immune sensor platforms to guide therapeutic design.",
        "raw_keywords": ["structural immunology", "cryo-EM", "TCR", "MHC", "B cell receptor", "drug design"],
        "raw_skills": ["cryo-EM", "protein purification", "biochemistry", "structural biology"],
        "working_style": "wet",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Comparative Medicine)",
        "pi": "Saurabh Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Uses comparative genomics and model organism studies to understand mammalian aging and longevity, studying long-lived species such as naked mole rats, bowhead whales, and Greenland sharks.",
        "raw_keywords": ["comparative medicine", "aging", "longevity", "naked mole rat", "comparative genomics", "geroscience"],
        "raw_skills": ["comparative genomics", "cell culture", "bioinformatics", "R"],
        "working_style": "dry",
        "undergrad_friendly": "unknown",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Neuroimaging Methods)",
        "pi": "Tanuja Bhatt",
        "department": "neuroscience",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Develops novel fMRI acquisition sequences, denoising algorithms, and connectivity analysis pipelines to improve sensitivity and reproducibility of human neuroimaging studies.",
        "raw_keywords": ["neuroimaging", "fMRI", "connectivity", "denoising", "methods", "neuroscience"],
        "raw_skills": ["fMRI", "MATLAB", "Python", "signal processing"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
    {
        "name": "Bhatt Lab (Bioethics and AI)",
        "pi": "Anjali Bhatt",
        "department": "internal medicine",
        "contact_email": "",
        "lab_url": "",
        "raw_description": "Conducts empirical bioethics research on the ethical, legal, and social implications of AI in clinical medicine, genomics, and precision health, with a focus on algorithmic fairness and patient autonomy.",
        "raw_keywords": ["bioethics", "AI ethics", "algorithmic fairness", "genomics", "precision medicine", "health equity"],
        "raw_skills": ["qualitative methods", "survey design", "R", "policy analysis"],
        "working_style": "dry",
        "undergrad_friendly": "yes",
        "openings_status": "unknown",
    },
]


def main():
    out = {"labs": LABS}
    OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {len(LABS)} labs → {OUT}")
    print("Next: python tag_labs.py")


if __name__ == "__main__":
    main()
